### ISSUE TITLE
Super Metroid In-game Controller Remapping has no effect.

### ISSUE THREAD

**Issue by Heffenfeffer** [tewtal/alttp_sm_combo_randomizer#10]
Console or Emulator:

OpenEmu 2.0.5

Original Filename: SMALttP - no-glitches-v8.1_normal-open_randomized-ganon_combo_180827369

Seed: 180827369

Item, Entrance or Custom: Start of Game

Mode: n/a
Logic: n/a
Goal: n/a
Difficulty: n/a 
Variation: n/a

Description of problem: Remapping the controls in Super Metroid on the file screen before starting gameplay doesn't have any effect. I tried to change the functions to Y-shoot B-jump X-Item Cancel A-Dash, but the controls remain X-shoot A-jump Y-Item Cancel B-Dash. Remapping the controls on the emulator will cause ALttP's controls to become similarly reversed.

Spoiler (if available): That said, this is still a wonderful idea and I really want to see it progress!

**Comment by SmolBig** [comment]
I'm unable to recreate this issue. (I can map my buttons.)

Are you making sure to exit the menu using the "End" option in that menu?

**Comment by lenophis** [comment]
This can happen if the menu isn't exited properly so it saves, but it can also happen if you reset or go back to the main menu, since the controls won't stick until the game saves it proper.

But just in case it's something else, can you provide a step-by-step of what you're doing?

**Comment by tewtal** [comment]
I'm going to close this since I haven't had any other reports of this happening. If this is still a problem we'll have to reopen it.
