### ISSUE TITLE
Impossible seed?

### ISSUE THREAD

**Issue by Sandwiches21** [tewtal/alttp_sm_combo_randomizer#101]
Console or Emulator: Emulator (higan)

 If emulator state which emulator and version.

Original Filename: ?

Seed: 851260044

Item, Entrance, or Custom: Moon Pearl, Speed Booster, Magic Mirror, Ice Beam, Grapple Beam

Mode: open
Logic: Normal/No glitches
Goal: Defeat Ganon/Mother Brain
Difficulty: Hard
Variation: combo

Description of problem: At this point, I really need the Moon Pearl to do anything substantial. It's in Pink Maridia behind the speed booster blocks. The Speed Booster is in the spring ball room. To get that, I need the Grapple Beam or the Ice Beam to glitch through the floor. The Grapple Beam is in the Ice Palace, which requires the Moon Pearl, and the Ice Beam is in Turtle Rock, which also requires the Moon Pearl along with a few other things I can't get. The Magic Mirror might give me more options, but that's the item I'd get from the blacksmith brothers, and that also requires the Moon Pearl. Is this impossible?

Spoiler (if available):

**Comment by drb647** [comment]
As of 10.0, hard difficulty logic includes using snails to clip through the aqueduct speed blocks.  Sounds like it's required for your seed.  Lucky you ;)

https://youtu.be/2pkBKvzeOec

**Comment by Sandwiches21** [comment]
Thanks for the tip! More than anything, I'm just glad there aren't any completely impossible seeds yet. I don't think anything else could be more frustrating than playing for hours when it's impossible to complete the game. Thanks again, community! Love the project!
