### ISSUE TITLE
"Reserve Tank, Brinstar" without Morph Ball

### ISSUE THREAD

**Issue by Hiveul** [tewtal/alttp_sm_combo_randomizer#102]
Original Filename: SMALttP - valttp-no-glitches-v10.1_normal-open-randomized-ganon_combo_141281238

"meta": {
        "difficulty": "normal",
        "variation": "combo",
        "logic": "alttp-no-glitches-v10.1",
        "sm_logic": "sm-normal",
        "rom_mode": "NoMajorGlitches",
        "seed": 141281238,
        "goal": "ganon",
        "build": "2018-11-20",
        "mode": "open",
        "weapons": "randomized",
        "morph": "randomized"
    }

Description of problem: It doesn't seem like the logic takes into account that the morph ball is randomized. Reaching "Reserve Tank, Brinstar" in step 2 is hard enough without morph ball to be able to use the bombs and super bombs I have, but it seems impossible to leave the room and go back to Zelda after getting the item. At least, at the glitch level I selected, I'm unable to do anything after reaching it. It's obvious I need to get that one, because it doesn't seem like I can reach the other glove or the morph ball anytime soon with my current kit.

I'm also wondering about "Energy Tank, Brinstar Ceiling", considering what little items I had, I had to do the tapping trick for the faster shinespark to get to it... Is that normal in the logic or am I missing something?

Spoiler (if available):

"playthrough": {
        "1": {
            "Light World": {
                "Kakariko Well - Bottom": "Energy Tank",
                "Blind's Hideout - Top": "Speed Booster",
                "Blind's Hideout - Right": "Fire Rod",
                "Mushroom": "Moon Pearl",
                "Mini Moldorm Cave - NPC": "Energy Tank",
                "Maze Race": "Super Missile",
                "Sunken Treasure": "Power Bomb"
            },
            "Hyrule Castle": {
                "Sanctuary": "Magic Mirror"
            },
            "Eastern Palace": {
                "Eastern Palace - Cannonball Chest": "Progressive Sword",
                "Eastern Palace - Map Chest": "Eastern Palace Big Key"
            }
        },
        "2": {
            "Brinstar": {
                "Reserve Tank, Brinstar": "Progressive Glove",
                "Energy Tank, Brinstar Ceiling": "Book Of Mudora"
            }
        },
        "3": {
            "Hyrule Castle": {
                "Sewers - Secret Room - Left": "Ice Rod"
            },
            "Desert Palace": {
                "Desert Palace - Map Chest": "Desert Palace Big Key"
            }
        },
        "4": {
            "Desert Palace": {
                "Desert Palace - Big Key Chest": "Lamp",
                "Desert Palace - Compass Chest": "Magic Cape",
                "Desert Palace - Prize": "Crystal 3"
            }
        },
        "5": {
            "Eastern Palace": {
                "Eastern Palace - Big Key Chest": "Bombs"
            }
        },
        "6": {
            "Castle Tower": {
                "Agahnim": "Defeat Agahnim"
            }
        },
        "7": {
            "Dark World": {
                "Catfish": "Hookshot"
            }
        },
        "8": {
            "Dark World": {
                "Hype Cave - Middle Left": "Morphing Ball",
                "Digging Game": "Varia Suit"
            },
            "Skull Woods": {
                "Skull Woods - Compass Chest": "Progressive Glove"
            }
        },
        "9": {
            "Dark World": {
                "Hookshot Cave - Bottom Right": "Charge Beam"
            },
            "Crateria": {
                "Missile (Crateria gauntlet right)": "Quake"
            },
            "Brinstar": {
                "Kraid": "Defeat Kraid"
            },
            "Norfair": {
                "Reserve Tank, Norfair": "Flippers",
                "Missile (Norfair Reserve Tank)": "Cane Of Somaria"
            },
            "Wrecked Ship": {
                "Missile (Wrecked Ship top)": "Progressive Sword",
                "Phantoon": "Defeat Phantoon"
            }
        },
        "10": {
            "Ice Palace": {
                "Ice Palace - Compass Chest": "Gravity Suit",
                "Ice Palace - Spike Room": "Ice Palace Big Key"
            }
        },
        "11": {
            "Maridia": {
                "Missile (yellow Maridia super missile)": "Hammer",
                "Super Missile (pink Maridia)": "Bombos",
                "Draygon": "Defeat Draygon"
            }
        },
        "12": {
            "Swamp Palace": {
                "Swamp Palace - Prize": "Crystal 7"
            },
            "Ice Palace": {
                "Ice Palace - Prize": "Crystal 1"
            },
            "Turtle Rock": {
                "Turtle Rock - Compass Chest": "Bow",
                "Turtle Rock - Roller Room - Left": "Turtle Rock Big Key"
            }
        },
        "13": {
            "Eastern Palace": {
                "Eastern Palace - Prize": "Crystal 5"
            },
            "Dark Palace": {
                "Palace of Darkness - Map Chest": "Palace of Darkness Big Key"
            }
        },
        "14": {
            "Dark Palace": {
                "Palace of Darkness - Big Chest": "Flute",
                "Palace of Darkness - Prize": "Crystal 4"
            },
            "Turtle Rock": {
                "Turtle Rock - Prize": "Crystal 6"
            }
        },
        "15": {
            "Misery Mire": {
                "Misery Mire - Spike Chest": "Misery Mire Big Key"
            },
            "Lower Norfair": {
                "Ridley": "Defeat Ridley"
            }
        },
        "16": {
            "Misery Mire": {
                "Misery Mire - Prize": "Crystal 2"
            },
            "Tourian": {
                "Mother Brain": "Defeat Mother Brain"
            }
        },
        "17": {
            "Ganons Tower": {
                "Ganon's Tower - DMs Room - Bottom Right": "Ganons Tower Big Key"
            }
        },
        "18": {
            "Ganons Tower": {
                "Agahnim 2": "Defeat Agahnim 2"
            }
        },
        "19": {
            "Dark World": {
                "Ganon": "Triforce"
            }
        },
        "longest_item_chain": 19,
        "regions_visited": 33
    }

**Comment by drb647** [comment]
Where exactly are you stuck going to/from Reserve Tank Brinstar?  Neither of these require multiple tapping or stuttering, just take a step or two before pressing & holding the run button.  You'll shorten your charge time enough to charge a spark in both the ceiling e-tank room and the Crateria parlor (to get through the wall leading to Jungle Brinstar).

**Comment by Hiveul** [comment]
https://imgur.com/a/CGtPViP

You mean this room here I'm supposed to be able to leave with just the speed booster and under normal difficulty logic?

**Comment by tewtal** [comment]
Yes, you can go back out by taking the top route, getting the item at the top left and then falling down through the crumble blocks.
