### ISSUE TITLE
Sponge Bath Strats required in seed generated under v10.1 Normal Logic

### ISSUE THREAD

**Issue by RupeeClock** [tewtal/alttp_sm_combo_randomizer#103]
Console or Emulator: Emulator - Retroarch BSNES Balanced core

Original Filename: SMALttP - valttp-no-glitches-v10.1_normal-open-randomized-ganon_combo_678237364

Seed: 678237364

Super Metroid and A Link to the Past Item Randomizer (v10.1)
Logic: ALttP no glitches, SM Normal
Goal: Defeat Ganon + Mother Brain
Difficulty: Normal
Variation: ALTTP+SM Combo Randomizer

Description of problem: 
Normal Logic expects the following
- ALttP: Not expected to navigate dark rooms without lamp
- SM: Not expected to navigate Maridia or water without Gravity Suit
- SM: Not expected to require [Wrecked Ship Sponge Bath strats](https://www.youtube.com/watch?v=8ldQUIgBavw&feature=youtu.be&t=36)
My normal logic seed generated the following
- "Link's House": "Progressive Glove",
- "Lumberjack Tree": "Progressive Glove",
- "Energy Tank, Wrecked Ship": "Lamp",
- "Crateria": {"Energy Tank, Terminator": "Morphing Ball"}
- "Brinstar": {"Morphing Ball": "Bombs"}
- "Brinstar": {"Power Bomb (blue Brinstar)": "Speed Booster"}
- "Lower Norfair": {"Energy Tank, Firefleas": "Gravity Suit"}
- "Swamp Palace - Big Chest": "Hi-Jump Boots",
- "Maridia": {"Spring Ball": "Space Jump"}

My run reached a point where most casually accessible areas appeared to be exhausted and I lacked progression items such as Varia Suit, Gravity Suit, Bow, Book of Mudora, Mirror, Space Jump, and beating Agahnim's Tower was necessary to get Titan's Mitt glove upgrade.
Clearing Agahnim's Tower requires Lamp for dark room navigation.
Limited equipment in Super Metroid meant I was without Varia Suit, Gravity Suit, Spring Ball, High Jump, Space Jump.
Lamp is located in the Energy Tank room in Wrecked Ship just past Sponge Bath room.
This meant that Sponge Bath strats requiring either Speed Booster, or Morphing Ball + (Power) Bombs is required to retrieve Lamp, to clear Agahnim's Tower and continue the run.

Some other hard logic tricks were attempted such as [Pink Brinstar Hopper Room Gate Glitch](https://wiki.supermetroid.run/Pink_Brinstar_Hopper_Room) (which yielded early Hammer) and hells-run navigation of Norfair, but this still did not allow for further progression.

Spoiler (if available):
[SMALttP - valttp-no-glitches-v10.1_normal-open-randomized-ganon_combo_678237364.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2753331/SMALttP.-.valttp-no-glitches-v10.1_normal-open-randomized-ganon_combo_678237364.txt)

Playthrough excerpt:
"playthrough": {
        "1": {
            "Light World": {
                "Sahasrahla's Hut - Right": "Energy Tank",
                "Kakariko Well - Bottom": "Magic Cape",
                "Bottle Merchant": "Screw Attack",
                "Link's House": "Progressive Glove",
                "Mini Moldorm Cave - Left": "Fire Rod",
                "Mini Moldorm Cave - Right": "Bombos"
            },
            "Hyrule Castle": {
                "Link's Uncle": "Super Missile",
                "Secret Passage": "Power Bomb"
            },
            "Eastern Palace": {
                "Eastern Palace - Cannonball Chest": "Eastern Palace Big Key"
            },
            "Brinstar": {
                "Morphing Ball": "Bombs"
            }
        },
        "2": {
            "Hyrule Castle": {
                "Sewers - Secret Room - Left": "Pegasus Boots",
                "Sewers - Secret Room - Middle": "Progressive Sword",
                "Sewers - Secret Room - Right": "Reserve Tank"
            },
            "Crateria": {
                "Energy Tank, Terminator": "Morphing Ball"
            }
        },
        "3": {
            "Brinstar": {
                "Charge Beam": "Progressive Sword",
                "Power Bomb (blue Brinstar)": "Speed Booster",
                "Energy Tank, Kraid": "Energy Tank",
                "Kraid": "Defeat Kraid"
            }
        },
        "4": {
            "Wrecked Ship": {
                "Missile (Gravity Suit)": "Cane Of Somaria",
                "Energy Tank, Wrecked Ship": "Lamp",
                "Right Super, Wrecked Ship": "Moon Pearl",
                "Phantoon": "Defeat Phantoon"
            }
        },
        "5": {
            "Castle Tower": {
                "Agahnim": "Defeat Agahnim"
            }
        },
        "6": {
            "Light World": {
                "Lumberjack Tree": "Progressive Glove"
            }
        }
}

**Comment by drb647** [comment]
Normal logic sponge bath requirement is one of: Space Jump, Gravity Suit, Hi Jump or Speed Booster.  Shouldn't be terribly difficult with any of them.

**Comment by tewtal** [comment]
Indeed, if you have speed booster you're expected to use that to get through. It's a fairly straight forward jump out of the water as long as you build up speed in the previous room.
