### ISSUE TITLE
Walljump into Gauntlet required in Normal logic in v10.1

### ISSUE THREAD

**Issue by viewtyjoe** [tewtal/alttp_sm_combo_randomizer#104]
Seed: Lassad Ti

Item, Entrance or Custom: Item

Mode: 
Logic: Normal No Glitches
Goal: 
Difficulty: 
Variation: Randomized Morph, Randomized Sword

Description of problem: Walljump into Gauntlet required for Space Jump which should not be in logic for this mode

Spoiler (if available): See attached file
[SMALttP_-_sm-normal_alttp-no-glitches-v10.1_normal-open_swords-randomized_morph-randomized_ganon_com.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2775991/SMALttP_-_sm-normal_alttp-no-glitches-v10.1_normal-open_swords-randomized_morph-randomized_ganon_com.txt)

**Comment by tewtal** [comment]
Looking at the spoiler log you have Bombs available to you which means that the intended method seems to be Infinite Bomb Jumps to get there which is something that is in logic for Normal seeds.
