### ISSUE TITLE
Possible Maridia Logic Problem on Hard

### ISSUE THREAD

**Issue by Sandwiches21** [tewtal/alttp_sm_combo_randomizer#106]
Console or Emulator: higan

 If emulator state which emulator and version.

Original Filename: 

Seed: 72156405

Item, Entrance or Custom: 

Mode: Normal
Logic: SM-Hard, LttP-No Glitch
Goal: Kill MoBrain and Pigguy
Difficulty: Hard
Variation: 

Description of problem: Possible logic problem, depending on tricks required. I have Morph, Varia, Spring Ball, Speed Booster, Bombs, PBs, Missles, Supers, Space Jump, and all beams but Spazer. I need the Gravity Suit to traverse much of Maridia, and it's in Turtle Rock big key chest. I can't get in Turtle Rock without the block cane, and Somaria is in Maridia, at Spring Ball. I don't think the floor glitch works without the extra vertical velocity from grav suit, so am I left trying to get into the hole from the grapple block with a jump trick or blue suit?

Spoiler (if available):

**Comment by cassidoxa** [comment]
Hi Sandwiches21. Hard logic intends you to have grapple beam, spring ball, and high jump for this (among some other items). It will never require an ice clip to get to spring ball. The logic expects you to remove the grapple block with the grapple beam and spring ball jump through the gap without gravity suit. Alternatively, you can gravity jump from the sand after removing the grapple block, although this is much harder and will never be required either. 

Grapple beam is available with the items you have and which are available to you. Here is a tutorial covering the mid air spring ball jump that will let you access this location: https://www.twitch.tv/videos/147442861

**Comment by Sandwiches21** [comment]
Thanks for the tutorial! Issue closed.
