### ISSUE TITLE
Lower Norfair Lava Room Chozo

### ISSUE THREAD

**Issue by SamHetfield** [tewtal/alttp_sm_combo_randomizer#107]
The Chozo that lowers the lava from this room doesn't seem to be working as intended. I got the green shuttle glitch to reach the Golden Torizo, but since the blocks on the left side are crumbling blocks there's no feasible way to go around and reach the item. (in my particular case it's a Fire Rod, so bye bye Skull Woods, bye bye Crystal 7, bye bye run)

I'll try to maneuver around some more and get a couple more items before I return, but nevertheless this segment might cause some trouble to other folks so I just wanted to point that out.

Thank you for your time, and keep up the great work!

BTW, my run is sm-normal_alttp-no-glitches-v10.2_normal-open_morph-vanilla_ganon_combo_148414871 

<img width="1280" alt="captura de tela 2019-02-23 as 21 16 08" src="https://user-images.githubusercontent.com/26654748/53294211-456c2d80-37b0-11e9-8926-2ade809e9316.png">

**Comment by CapnCrinklepants** [comment]
I noticed before you edited that you said you have neither Screw Attack nor Space Jump. Welp, for whatever reason, Nintendo coded that statue to only work if you have Space Jump, so your run isn't RIP; you simply need to find Space Jump first. It's not obvious, especially to people new to SM, so I understand your confusion, but it most likely isn't broken.

**Comment by SamHetfield** [comment]
oh wow, I'm dumb

seriously, though, thanks a bunch for the help
