### ISSUE TITLE
Impossible logic on Normal

### ISSUE THREAD

**Issue by ShadowKitty42** [tewtal/alttp_sm_combo_randomizer#108]
Console or Emulator: Emulator, Snes9x v1.54

 If emulator state which emulator and version.

Original Filename: SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-randomized_ganon_combo_736668249

Seed: 736668249

Item, Entrance or Custom: Item

Description of problem: Progressive item impossible to get on Normal difficulty.
![Screenshot_2](https://user-images.githubusercontent.com/3394296/55586874-e5d23d80-56de-11e9-8d03-83aa9f09f137.png)
According to the spoiler, with the items I had above, my next item was Progressive Glove at Energy Tank, Wrecked Ship. I don't see how it's possible to get there.

Spoiler (if available):
[SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-randomized_ganon_combo_736668249.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/3045365/SMALttP.-.sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-randomized_ganon_combo_736668249.txt)

**Comment by TomFaulkner** [comment]
There are several options for getting through the Sponge Bath in Wrecked Ship.
https://wiki.supermetroid.run/Sponge_Bath

**Comment by ShadowKitty42** [comment]
I wasn't aware of all those techniques or that they would be required in NORMAL logic.
The Sponge Bath strats on the following document are specifically listed under HARD logic.
https://docs.google.com/document/d/1fP-DRbuROuQ-zifwKftuV-Paoh0_GGYErLGv3VVAg7Y/edit

**Comment by drb647** [comment]
Sponge Bath with Hi-Jump, Space Jump and Speed Booster are listed under Normal logic in that doc.  Speed Booster isn't too bad: start all the way to the end of the ledge in the previous room and run into Sponge Bath, jump about halfway through the pool, and walljump up.  No short charge required.
