### ISSUE TITLE
Impossible seed

### ISSUE THREAD

**Issue by robertpw1983** [tewtal/alttp_sm_combo_randomizer#11]
Seed: 332884433

Description of problem: Bottom line is, can't access the Morphing Ball without the Moon Pearl and vice versa.

Spoiler (if available): 
[SMALttP - no-glitches-v8.1_normal-open_randomized-ganon_combo_332884433.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2019133/SMALttP.-.no-glitches-v8.1_normal-open_randomized-ganon_combo_332884433.txt)

**Comment by tewtal** [comment]
Yep, this is confirmed a bug in the SM logic and will be fixed in the next update. Thanks for reporting this.

**Comment by tewtal** [comment]
This is now fixed and released in v9
