### ISSUE TITLE
Morph Ball Locked by logic

### ISSUE THREAD

**Issue by MINICHE79** [tewtal/alttp_sm_combo_randomizer#110]
Console or Emulator: Emulator, Snes9x v1.57

 If emulator state which emulator and version.

Original Filename: SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_morph-randomized_ganon_combo_206586295.sfc

Seed: 206586295

Item, Entrance or Custom: Item

Mode: open
Logic: sm-normal
Goal: ganon
Difficulty: normal
Variation: combo

Description of problem:
according to the spoiler the "Morph Ball" is in the "Bombos Tablet"
to get to the "Bombos Tablet" you need "Magic Mirror"(obtainable) and the two "Gloves" or the "Hammer" or the "Flute" 
One of the "Gloves" is in the "Swamp palace"
The Flute is in "Lower Norfair - Power Bombs of Shame" (You need "Morph Ball")
And the "Hammer" is in the "Missile - Hi-Jump Boots" (Also needed "Morph Ball")
So...
Spoiler (if available):
[SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_morph-randomized_ganon_combo_206586295.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/3096984/SMALttP.-.sm-normal_alttp-no-glitches-v10.2_normal-open_morph-randomized_ganon_combo_206586295.txt)

**Comment by drb647** [comment]
Beating Aghinim gets you to Dark World without gloves of hammer.  You have access to two sword upgrades and the hookshot, that's enough beat Aghinim and get you to the Bombos tablet.

**Comment by MINICHE79** [comment]
> Beating Aghinim gets you to Dark World without gloves of hammer. You have access to two sword upgrades, flippers and hookshot, so you can beat Aghinim, cross the river in the Dark World on the way to Catfish, grab the first glove in Village of Outcasts, and head on to Bombos Tablet.

The problem is that I can't go to the bombos tablet even after beating Aghinim
![Zelda](https://user-images.githubusercontent.com/31643234/56513621-48ee0d80-64f0-11e9-8952-f7c3d83c7f09.png)

**Comment by drb647** [comment]
There's a space to drop down on the other side of the rock pictured.  That one threw me for a loop too when I started.
