### ISSUE TITLE
Morph Ball locked behind logic 

### ISSUE THREAD

**Issue by darkzero7222** [tewtal/alttp_sm_combo_randomizer#111]
Console or Emulator: snes9x-1.59.2

 If emulator state which emulator and version.

Original Filename: SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-randomized_ganon_combo_69148013

Seed: 69148013

Item, Entrance or Custom: 

Mode: open
Logic: sm-normal
Goal: ganon
Difficulty: normal
Variation: combo

Description of problem: 
Morph Ball locked in Mire Shed Left which needs Quake to access. Have all items to get to me to Misery Mire except for Quake. Quake hiding in Maridia right sand pit room where the Power Bomb is normally, which cannot be accessed without a few items, most importantly the Morph Ball. Haven't tried going into Maridia yet but watching a video of someone doing it shows that in the right pit you need the Morph Ball to access the Power Bomb item, which in my seed is the Quake Medallion. At this point I believe I cannot progress in any of the games.

Spoiler (if available):

**Comment by drb647** [comment]
Mire shed doesn't require a medallion as it's outside of the dungeon proper.  As long as you can get to the swamp you can get to the shed (to the left of the dungeon entrance).

**Comment by darkzero7222** [comment]
Ah I'm an idiot, i got to Misery Mire and just saw the medallion on the floor and though that was it. Thank you for letting me know
