### ISSUE TITLE
Aquired the Magic Powder before Mushroom

### ISSUE THREAD

**Issue by RotatoHead** [tewtal/alttp_sm_combo_randomizer#112]
Console or Emulator: SNES9X 1.53

Original Filename: SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-vanilla_ganon_combo_179493563

Seed: 179493563

Item, Entrance or Custom: Mushroom/Magic Powder

Mode: NoMajorGlitches
Logic: alttp-no-glitches-v10.2
Goal: ganon
Difficulty: normal
Variation: combo

Description of problem:
I acquired the magic powder before getting the mushroom, which caused me to be unable to access the potion shop reward. It isn't game-breaking, as after checking the spoiler, the item was only a Heart Container, which leads me to believe that this may be intentional, as no key items were locked behind it. I just thought I'd mention it.

Spoiler (if available): [SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-vanilla_ganon_combo_179493563.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/3099600/SMALttP.-.sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-vanilla_ganon_combo_179493563.txt)

**Comment by drb647** [comment]
Highlight the mushroom and press Y to toggle to the powder.  Same for flute/shovel and wooden/silver arrows.  https://docs.google.com/document/d/1fP-DRbuROuQ-zifwKftuV-Paoh0_GGYErLGv3VVAg7Y

**Comment by RotatoHead** [comment]
Oh, thanks for clearing that up.
