### ISSUE TITLE
Is it even possible to IBJ with Power Bombs? 

### ISSUE THREAD

**Issue by Teal-chan** [tewtal/alttp_sm_combo_randomizer#113]
Console or Emulator: BSNES 0.5.0 Mac

 If emulator state which emulator and version.

Original Filename:

Seed: 826527507

Item, Entrance or Custom: Hookshot, Morph Bombs

Mode: Normal
Logic: Normal
Goal: Ganon
Difficulty: Normal
Variation: None

Description of problem:

Surely I am not expected to IBJ with Power Bombs to obtain the hookshot here, since the bombs themselves are in the Mickey Mouse room, which still cannot be accessed with current equipment.
.
<img width="848" alt="Screen Shot 2019-04-20 at 1 09 02 PM" src="https://user-images.githubusercontent.com/28679609/56461298-7eb6b900-636d-11e9-816c-b03f87d404d8.png">

Spoiler (if available):

**Comment by Teal-chan** [comment]
I should also clarify, the Charge Beam, which is needed to defeat the Golden Torizo, is also inaccessible with current equipment. Basically, I need the Quake medallion to open Misery Mire, which is not possible at the moment.

**Comment by drb647** [comment]
Not really as you can only have one PB on-screen at a time.  Both of those pickups should be reachable with single bomb jumps and a tight mid-air morph - if you have HiJump it helps to turn it off.

**Comment by Teal-chan** [comment]
Morph ball bombs are in Ganon's tower.

For the record, I can do the IBJ just fine, just not when the bombs are an endgame item like that.
