### ISSUE TITLE
Ice Palace Softlock

### ISSUE THREAD

**Issue by Shauing** [tewtal/alttp_sm_combo_randomizer#114]
Console or Emulator: SNES9X v1.56.1 

 If emulator state which emulator and version.

Original Filename:

Seed: 66034837

Item, Entrance or Custom: 

Mode: Normal
Logic: Normal
Goal: Ganon
Difficulty: Normal
Variation: None

Description of problem: A key necessary to solve a puzzle in B6 to reach the boss on the Ice Palace is given when said boss is defeated. Had to learn a skip (bomb jump) in order to reach the boss.

![SMALttP - valttp-no-glitches-v10 2_normal-open-ganon_combo_66034837005](https://user-images.githubusercontent.com/49821906/56462984-bcc5d400-6391-11e9-9cc4-45543f11f592.png)

![SMALttP - valttp-no-glitches-v10 2_normal-open-ganon_combo_66034837001](https://user-images.githubusercontent.com/49821906/56462961-4aed8a80-6391-11e9-8a66-67ce02ffef12.png)

![SMALttP - valttp-no-glitches-v10 2_normal-open-ganon_combo_66034837002](https://user-images.githubusercontent.com/49821906/56462964-4e811180-6391-11e9-8f5b-3fa479ea79ea.png)

Spoiler (if available):

**Comment by drb647** [comment]
Boss can drop a key when the logic expects Cane of Somaria before Ice Palace.  Can't say for sure without a spoiler file, but IPBJ should never be required for Normal logic.

**Comment by Shauing** [comment]
Here's the spoiler file. Also, I couldn't find the Red Mail in this text.

[SMALttP - valttp-no-glitches-v10.2_normal-open-ganon_combo_66034837.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/3105080/SMALttP.-.valttp-no-glitches-v10.2_normal-open-ganon_combo_66034837.txt)

**Comment by tcprescott** [comment]
Somaria is on Helmasaur King and Bow, Hammer, and Moon Pearl are accessible, along with dark world access.  Game is expecting you to do PoD for Somaria.

**Comment by Shauing** [comment]
Lamp is also needed in order to see where to go, which is located on Pink Maridia, which can't be accessed without Gravity Suit. The suit is located on Lower Norfair, which cannot be reached due to lava. There is an access located closer to the Misery Mire dungeon, but it needs Space Jump and Screw Attack. Space Jump is located on Wrecked Ship, which cannot be reached due to an area filled with water, and can only be crossed with the Grappling Beam...which is also located on Pink Maridia.

**Comment by drb647** [comment]
Getting to Ridley from the Mire portal doesn't require Space Jump or Screw Attack, though one or both does make it easier.  Grapple or Gravity are not rquired for any of the Wrecked Ship pickups, Speed Booster will get you across the moat and through the flooded rooms on the way to where the Reserve Tank is in vanilla (which is where your lamp is).

**Comment by Shauing** [comment]
Ok. By the way, where is the red tunic? What name has in this text? I can't find it.

**Comment by drb647** [comment]
They're labeled as "progressive armor"; first one you find will be blue, the 2nd will be red.  They're in Retro Brinstar and Lower Norfair.
