### ISSUE TITLE
Need help to get to Maridia Right Sand Pit

### ISSUE THREAD

**Issue by darkzero7222** [tewtal/alttp_sm_combo_randomizer#116]
Console or Emulator: snes9x1.59.2

 If emulator state which emulator and version.

Original Filename:
SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-randomized_ganon_combo_69148013
Seed:
69148013 
Item, Entrance or Custom: 

Mode: open
Logic: sm-normal
Goal: ganon
Difficulty: normal
Variation: combo

Description of problem:
As the title suggest I desperately need to get to Maridia's right sand pit. I do not have the Gravity Suit, Morph Bombs or High Jump Boots but I do have the Ice Beam and Space Jump. In the sand pit is where the Quake Medallion is, and in Turtle Rock is where the Gravity Suit is. I already have the the Cane of Somaria so I think that's all I will need for Turtle Rock other then the Quake Medallion. Any help would be greatly appreciated. Thanks!

Spoiler (if available):
Morph Bomb: Ganon's Tower (ain't happening)
Speed Boots: Lower Norfair (also ain't happening)
High Jump Boots (Green Maridia Shinespark, my guess that first missile at the beginning)

**Comment by drb647** [comment]
This may be a dumb question, but did you verify that TR is locked by Quake?  The entrance medallion is randomized...  Otherwise, you may be able to get to the pits without Gravity from either the back of the Wrecked Ship or the crossover portal at Dark World Lake Hylia, though getting the items out of the pit is still gonna be rough.  Check the medallion and I'll research the path.

**Comment by darkzero7222** [comment]
Oh wow I didn't think the medallion entrances were randomized too. I haven't gone to Turtle Rock I just assumed based on playing normally which apparently has been messing me up quite a bit during this Randomizer run. I have the other two medallions so when I get back home after work I'll go check to see what medallion I actually need. Thank you very much for the help

**Comment by darkzero7222** [comment]
Oh my god I finally caught a break the entrance for Turtle Rock was changed to the Ether Medallion. Sorry to bother you guys, thanks for the help!
