### ISSUE TITLE
Sorry, noob to this and need help

### ISSUE THREAD

**Issue by mclark1502** [tewtal/alttp_sm_combo_randomizer#117]
Good day, i'm new to randomizers and REALLY want to play this.

however, it isn't letting me merge the games. I think I have the specific games to do it but it says roms not recongised when putting them in the browser. 

Does anyone have a link to the specific 2 roms I need for this just to make sure I have the right ones? 

sorry to be a pain, i'm new to this kind of thing. My apologies.

**Comment by tcprescott** [comment]
We can't link to ROMs.  However what you'll need is the Super Metroid USA/Japan release, and the Link to the Past Japan 1.0 release (if it says Rev1/Rev2 or 1.1/1.2 it isn't the right ROM).  Link to the Past should be roughly named "Zelda no Densetsu - Kamigami no Triforce (J) (V1.0)".

**Comment by mclark1502** [comment]
I'm 99% sure the metrois one is right but at for zelda, the only one specific to that name is on sites that says they no longer do it when you download it. 

does it have to say Kamigami no Triforce because I do have one of that but it doesnt say what version it is. it doesn't specifically say (j) but it is japanese. 
Can also see many that just say Zelda no Densetsu without the second bit but is V1.0

i'm completely new to this. confusing me. I'm trialling and erroring this. 

thanks for the reply matey

**Comment by mclark1502** [comment]
never mind, sound the right one.

thanks a bunch matey, you are a legend. thank you.

would you recommend a good controller for this?

**Comment by tcprescott** [comment]
Me personally? No (I play on console).  If you ask in the SMZ3 discord there are a ton of very helpful people there that could recommend a controller: https://discord.com/invite/PMKcDPQ
