### ISSUE TITLE
Bomb Jumping

### ISSUE THREAD

**Issue by bluedart** [tewtal/alttp_sm_combo_randomizer#118]
Hello there.  I seem to be nearing the end of the joint-randomizer.  I've played the Link to the Past randomizer casually around 30 times, so I'm quite familiar with it; however this is my first time attempting a Super Metroid randomizer.  ALttP is mostly done; I simply need the Bow and the Ether Medallion.  I've been using a map for Super Metroid to avoid missing things, and I already had to check the spoiler once before to find that the Gravity Suit was indeed somewhere I thought required the Gravity Suit, but in fact did not.  Now, from what I can tell, the items I need are all in Norfair.  Unfortunately equipped as I currently am I am unable to reach the area I need to as either entry point would require multiple bomb jumps, which I do not know how to do as they are neither taught nor hinted at in the game in any way.

Interestingly, I came across this tidbit in the Super Metroid x ALttp Resources google doc that I've been referencing to attempt to understand this randomizer.

> **I can’t infinite bomb jump/walljump/shinespark! Can we make an easier logic?**
> No. These are fundamental skills taught by the vanilla game in some fashion, and as such we have deemed it permissible for even simple logics to require these tricks.

This logic would be acceptable for wall-jumping and shinesparking, as it is backed by fact, and as such is present in the game in some way.  Etecoons and Dachoras teach wall-jumping and shinesparking respectively.  There is, however, no such analogous for infinite bomb-jumping in the game at all.  I therefore submit that it is not a "fundamental skill taught by the vanilla game".

I, and likely many, many other individuals, would like to see an extra set of logic, or even a separate option, added to the quizzically short list of options present in the randomizer.  Honestly, the only difference being it not requiring the statistically awkward skill of infinite bomb-jumping would be sufficient.

It's mostly academic at this point, but the spoiler is:
https://pastebin.com/Y4mq9JnG

The emulator I'm using is: RetroArch 1.7.6 / Snes9x 2010 d0606eb (core).

I will probably look into a Super Metroid bomb-jump tutorial anyway, since it may be a neat skill to have, but my inquiry stands regardless.  If there's somewhere the game teaches this skill I'd love to know about it.  Either way, is there a particular reason you've kept the options so bare-bones when the Link to the Past Randomizer is so extensible in that fashion?  Thanks for your time.

**Comment by drb647** [comment]
Bomb jumps (and some other tricks) are shown in the SM "attract reel" in Vanilla, hang around on the start screen long enough and it'll play.  I don't believe it plays in Randomizer, though. 
 https://www.youtube.com/watch?v=m7-Z4swEgKE

**Comment by bluedart** [comment]
Wow, that's interesting.  I didn't even know about that!  I'd be willing to bet most people don't either.  However, that definitely is in the game.  Neat.  Thanks for the info.

Also, my question was a two-parter.  

> Either way, is there a particular reason you've kept the options so bare-bones when the Link to the Past Randomizer is so extensible in that fashion?

Thanks again.

**Comment by tewtal** [comment]
Looks like this was resolved.
When it comes to further options, more will be added in future versions. It's been kept barebones so implementation from the start was easier since it's a pretty complex randomizer.
