### ISSUE TITLE
Impossible Seed? 

### ISSUE THREAD

**Issue by fillerbunny9** [tewtal/alttp_sm_combo_randomizer#124]
Console or Emulator: Emulator

 If emulator state which emulator and version.  Snes 9X 1.56.2

Original Filename: SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_morph-randomized_ganon_combo_504037014

Seed: 504037014 

Item, Entrance or Custom: 

Mode: Open
Logic: Normal
Goal: Ganon
Difficulty: Normal
Variation: Combo

Description of problem: Super Metroid Normal Logic requires getting to and beyond Ridley in order to obtain the Gravity Suit. I am not sure of the details of Normal vs Hard, but this does not seem like it belongs under Normal. 

[SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_morph-randomized_ganon_combo_504037014.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/3193665/SMALttP.-.sm-normal_alttp-no-glitches-v10.2_normal-open_morph-randomized_ganon_combo_504037014.txt)

Spoiler (if available): Gravity Suit is locked after the Ridley fight with Normal difficulty logic.

**Comment by jmontano86** [comment]
If I'm not mistaken, you can get to lower norfair by using the warp at the dark world ice rod cave.

**Comment by fillerbunny9** [comment]
no flippers, which are locked behind needing the cape, which is in Maridia.

**Comment by drb647** [comment]
Dark Ice Rod cave warps to the back of Maridia.  The LN warp is in Misery Mire - the shed to the right of the dungeon entrance.

**Comment by fillerbunny9** [comment]
thank you. is there a beginners guide to this at all which discusses item changes (I am at 65 Super Missiles right now which I know to be different) as well as the various warp points?

**Comment by drb647** [comment]
Linked on the front page of this site: https://docs.google.com/document/d/1fP-DRbuROuQ-zifwKftuV-Paoh0_GGYErLGv3VVAg7Y
