### ISSUE TITLE
cant find quake medallion

### ISSUE THREAD

**Issue by JordanB500** [tewtal/alttp_sm_combo_randomizer#127]
Console or Emulator:emulator

 If emulator state which emulator and version. snes9xgx(wii emulator)

Original Filename: unknown renamed for filesize.

Seed: -258190103

Item, Entrance or Custom:  Quake Medallion

Mode:  Normal
Logic:  Normal
Goal:  Defeat Mother Brain and Ganon
Difficulty: Normal
Variation: Normal

Description of problem: I previously played this seed without saves and now i am playing again however i cant seem to remember where i got the quake medallion (it was in the light world this much i know however when searching spoilers for quake there are 3 entries and i know there is only one quake medallion so something seems to be incorrect here any help would be appreciated

Spoiler (if available): currently have access to the top of turtle rock but no quake medallion like my last playthrough

also my emulator still isnt saving my games

**Comment by drb647** [comment]
Where exactly are you getting your spoilers from?  I generated the spoiler for your seed and Quake is listed once - at the missile below the Ice Beam in Norfair.  Also, your seed requires Bombos for Turtle Rock access, not Quake.

[258190103-spoiler.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/3208566/258190103-spoiler.txt)

**Comment by JordanB500** [comment]
i found it it was the chest in the sanctuary and the spoiler from the seed generated with spoilers
    On Wednesday, May 22, 2019, 12:28:10 PM CDT, drb647 <notifications@github.com> wrote:  
 
 
Where exactly are you getting your spoilers from? I generated the spoiler for your seed and Quake is listed once - at the missile below the Ice Beam in Norfair. Also, your seed requires Bombos for Turtle Rock access, not Quake.

258190103-spoiler.txt

**Comment by JordanB500** [comment]
this issue is resolved for me, i will write down the location so i will remember.
