### ISSUE TITLE
Unable to save game on any emulator, pc or console

### ISSUE THREAD

**Issue by JordanB500** [tewtal/alttp_sm_combo_randomizer#129]
Console or Emulator: Emulator

 If emulator state which emulator and version. Various

Original Filename: unknown shortened for convenience

Seed: 258190103(primary but same for all seeds)

Item, Entrance or Custom: ??? cant save the game properly only creates empty 0kb save files

Mode: N/A
Logic: N/A
Goal: Defeat ganon and your mom lol jk(mother brain)
Difficulty: N/A
Variation: N/A

Description of problem: when attempting to save the game  it only creates 0kb empty save files

Spoiler (if available):
(I tried for a while to get my emulator on console to save and now that it can i realized this one does not originally assuming it was the emulator and not the game)

a possible suggestion would be to create a mechanic where depending on where you last saved(which there would be a check for) it would load either of the save files and when saved it would save to each individual save file(if you gained items from both sides at once, if not then one would be saved and the other unmodified) this would be inside of a single file if that makes sense

if this doesnt work idk what to say other then the only option for playing is to keep the emulator on indefinitely! or use save states

**Comment by drb647** [comment]
From your post elsewhere:

Turtle Rock: I believe LTTP logic is OHKO compliant.  Regardless, you can get Cane of Bryna from Catfish and use it to get past the lasers.

Thieves Town: nothing requires the bow.  The only dungeons where bow is required are Eastern and Palace of Darkness.

Crateria: https://crocomi.re/163. Learn to quick charge, it's simple and helps immensely in SM: https://wiki.supermetroid.run/Quick_charging

This forum is designed for reporting issues with game code and logic, not so much gameplay assistance, and hijacking someone else's thread is never cool.  I'm willing to keep helping you if you post an email address that I can contact you at directly.

**Comment by JordanB500** [comment]
my apology i didnt know emailing was the same as a forum post ill close this issue shortly i meant to close it sooner and tbh i thought i did already and is there a way i can contact you in person instead of on this forum?

**Comment by drb647** [comment]
drbentleyccnp @ gmail . com
