### ISSUE TITLE
Doesn't work on ZSNES.

### ISSUE THREAD

**Issue by gjgfuj** [tewtal/alttp_sm_combo_randomizer#13]
Console or Emulator:

ZSNES V1.51 - Linux

Original Filename: SMALttP - sm-casual_alttp-no-glitches-v9.1_normal-open_swords-randomized_morph-randomized_ganon_combo_251816198.sfc
but also for every other rom I've tried

Description of problem: Gives just a black screen upon loading, zsnes says it is a bad rom. I'm not sure what else you might need from me, so who knows.

**Comment by tcprescott** [comment]
The A Link to the Past Randomizer never really worked well on ZSNES (in fact, on the latest version it doesn't work at all), and I have no reason to doubt that the combo randomizer would work any better on ZSNES.  I would recommend using Higan, Bsnes, or Snex9X 1.53+.  ZSNES is an outdated and very inaccurate emulator.

**Comment by tewtal** [comment]
This randomizer not working on ZSNES is not a bug indeed. It's instead ZSNES that's so buggy it can't run the randomizer properly. Using one of the emulators recommended in the previous comment should work fine and let you play without issues.
