### ISSUE TITLE
no gravity suit to get hammer

### ISSUE THREAD

**Issue by spt3m4** [tewtal/alttp_sm_combo_randomizer#134]
Console or Emulator: Emulator

 If emulator state which emulator and version. snes9x-1.52-win32.fix4

Original Filename: SMALttP - sm-normal_alttp-no-glitches-v10.2_normal-open_swords-randomized_morph-randomized_ganon_combo_486122779

Seed: 486122779

Item, Entrance or Custom: Item

Mode: No Glitches
Logic: Normal
Goal: ganon
Difficulty: normal
Variation: combo

Description of problem: I believe this seed is not solvable:
1) hammer is behind brinstar's e-tank location waterway (thus requiring gravity suit)  
2) hammer is in turn required to complete Palace of Darkness
3) which contains crystal 5
4) which is required to open pyramid fairy
5) which contains gravity suit

Spoiler (if available):

relevant section below (starred are the chain of requirements that are not able to be met)

        "7": {
            "Eastern Palace": {
                "Eastern Palace - Prize": "Crystal 6"
            },
            "Crateria": {
                "Power Bomb (Crateria surface)": "Cane Of Somaria",
                "Missile (Crateria moat)": "Charge Beam"
            },
            "Brinstar": {
                **"Energy Tank, Waterway": "Hammer"**,
                "Energy Tank, Kraid": "Progressive Sword",
                "Kraid": "Defeat Kraid"
            },
            "Wrecked Ship": {
                "Missile (Wrecked Ship top)": "Varia Suit",
                "Super Missile (Wrecked Ship left)": "Progressive Glove",
                "Phantoon": "Defeat Phantoon"
            }
        },
        "8": {
            "Tower Of Hera": {
                "Tower of Hera - Basement Cage": "Tower of Hera Big Key"
            },
            "Dark Palace": {
                "Palace of Darkness - The Arena - Bridge": "Progressive Sword"
            },
            "Skull Woods": {
                "Skull Woods - Compass Chest": "Skull Woods Big Key"
            },
            "Thieves Town": {
                "Thieves' Town - Compass Chest": "Thieves Town Big Key"
            },
            "Norfair": {
                "Missile (Speed Booster)": "Flute",
                "Wave Beam": "Flippers"
            }
        },
        "9": {
            "Tower Of Hera": {
                "Tower of Hera - Prize": "Crystal 3"
            },
            "Thieves Town": {
                "Thieves' Town - Prize": "Crystal 2"
            },
            "Ice Palace": {
                "Ice Palace - Spike Room": "Morph Bombs"
            }
        },
        "10": {
            "Skull Woods": {
                "Skull Woods - Prize": "Crystal 4"
            },
            "Lower Norfair": {
                "Ridley": "Defeat Ridley"
            }
        },
        "11": {
            "Dark Palace": {
                "Palace of Darkness - Dark Maze - Bottom": "Palace of Darkness Big Key"
            }
        },
        "12": {
            "Dark Palace": {
                **"Palace of Darkness - Prize": "Crystal 5"**
            }
        },
        "13": {
            "Dark World": {
                **"Pyramid Fairy - Left": "Gravity Suit"**
            }
        },

**Comment by spt3m4** [comment]
oh and i did try charging speed booster on the ledge above the speed blocks in the brinstar waterway, then dropping down to the water and spark left. Samus jumped and moved left a couple of pxiels but didn't spark. (The same key combo allowed me to spark left while still on the ledge so  it is probably not my technique) I tried it many times. Unless there is a trick that i don't know about....?

**Comment by spt3m4** [comment]
nevermind - jump then left - not simultaneously - did the trick sorry

**Comment by spt3m4** [comment]
BTW just out of curiosity i had high jump to get up to the ledge from the water on brinstar waterway so that i could charge a spark. Is that and/or space jump part of the logic when gravity is dependent on the item behind the speed blocks there?

**Comment by tewtal** [comment]
It's possible to get up there without hijump actually, so the logic should be correct.

**Comment by spt3m4** [comment]
ah okay. thanks. I must have assumed and got the water depth confused with the wrecked ship one (the one room with that single enemy before the spikes/kago room) where trying to initiate a wall jump is nigh impossible without aid.
