### ISSUE TITLE
Can't generate spoiler from filename

### ISSUE THREAD

**Issue by murphn86** [tewtal/alttp_sm_combo_randomizer#135]
Console or Emulator: Emulator

 If emulator state which emulator and version. Snes9x 1.59.2

Original Filename: SMALttP - sm-hard_alttp-no-glitches-v10.2_normal-open_morph-randomized_ganon_combo_YxMXAZOevz

Seed: YxMXAZOevz

Item, Entrance or Custom: 

Mode: open
Logic: alttp-no-glitches-v10.2
Goal: ganon
Difficulty: normal
Variation: combo

Description of problem: When I first generated this seed, I only generated the rom (no spoiler). I'm now trying to generate a spoiler from the website, but entering the seed from this file does not allow the full seed. It stops accepting characters before I can enter the last letter. Is there another way to find out which seed I am using?  

Spoiler (if available): N/A

**Comment by tewtal** [comment]
It looks like you've generated a race seed which does not include spoilers and there's no way to recover the spoiler unfortunately. Next time if you want to generate a seed where you can get a spoiler, make sure to not select the "race" option.
