### ISSUE TITLE
impossible seed

### ISSUE THREAD

**Issue by Vestavarr** [tewtal/alttp_sm_combo_randomizer#138]
Console or Emulator: emulator

 If emulator state which emulator and version.
snes9x, version 1.58
Original Filename:

Seed:527787881

Item, Entrance or Custom: 

Mode: NoMajorGlitches
Logic: alttp-no-glitches-v10.2
Goal: ganon
Difficulty: normal
Variation: combo

Description of problem:
The 2nd crystal is in the desert palace, the book of mudora is in Ganon's tower. cant access either without the opposite item
Spoiler (if available):

**Comment by jmontano86** [comment]
You can also get to desert palace by using mirror while in the swamp. If Titans mitts and flute aren't available yet, you can get to the swamp by one of the warp gates in Metroid, though I can't recall which one. Might be the one in maridia.

**Comment by Vestavarr** [comment]
oh! i did not know that with the mirror. that works then, thank you
