### ISSUE TITLE
Collecting Heart Pieces in SM does not complete new heart containers

### ISSUE THREAD

**Issue by SmolBig** [tewtal/alttp_sm_combo_randomizer#14]
Console or Emulator:
Snes9x

Seed: 342676451 (this is a recommended testing seed, with easy access to heart pieces)

Difficulty: Casual

Description of problem:
*Recreation steps*
*Collect 3 heart pieces in LttP.
*Go to SM and collect a heart piece. 
*Go back to LttP and instead of having a new heart your heart piece counter will be wrong

**Comment by tewtal** [comment]
I'll take a look at it, it should work in theory but it's very likely that there's a fun bug somewhere in the code that's supposed to fix this :)

**Comment by tewtal** [comment]
Fixed, will be in the next update.
