### ISSUE TITLE
Brinstar Blue Top Missiles without any upgrades

### ISSUE THREAD

**Issue by DJTeeJay80** [tewtal/alttp_sm_combo_randomizer#140]
Console or Emulator:

 If emulator state which emulator and version.

Original Filename:

Seed: 291939855

Item, Entrance or Custom: 

    "meta": {
        "difficulty": "normal",
        "variation": "combo",
        "logic": "alttp-no-glitches-v10.2",
        "sm_logic": "sm-normal",
        "rom_mode": "NoMajorGlitches",
        "seed": 291939855,
        "goal": "ganon",
        "build": "2019-02-17",
        "mode": "open",
        "weapons": "",
        "morph": "randomized"
    }

Description of problem:
Spoiler tells me to get the hammer from Brinstar blue top (chapter 4 of playthrough). But to get there I need to cross an invisible bridge in a flooded room. But I don't have the Gravity Suit so I can't move in the water - I can't even go back into the right door - when I have entered the room, I fall into the water and then I'm softlocked. How can I solve this? One idea was the bomb jump, but I also don't have the morph bombs. But they are in the Crateria Gauntlet, and actually I can reach that location only with walljumps - in normal logic that shouldn't be necessary.

Another question: Can the normal logic force me to enter Kraid's Lair using a well-timed walljump instead of the Hi-Jump-Boots?

Spoiler (if available):
{
    "Light World": {
        "Sahasrahla's Hut - Left": "Progressive Shield",
        "Sahasrahla's Hut - Middle": "Power Bomb",
        "Sahasrahla's Hut - Right": "Piece Of Heart",
        "Sahasrahla": "Twenty Rupees",
        "King Zora": "Mushroom",
        "Potion Shop": "Morphing Ball",
        "Zora's Ledge": "Three Bombs",
        "Waterfall Fairy - Left": "Missile",
        "Waterfall Fairy - Right": "Ten Arrows",
        "Master Sword Pedestal": "Grappling Beam",
        "King's Tomb": "Ten Arrows",
        "Kakariko Tavern": "Heart Container",
        "Chicken House": "Moon Pearl",
        "Kakariko Well - Top": "Twenty Rupees",
        "Kakariko Well - Left": "Piece Of Heart",
        "Kakariko Well - Middle": "Five Rupees",
        "Kakariko Well - Right": "Missile",
        "Kakariko Well - Bottom": "Piece Of Heart",
        "Blind's Hideout - Top": "Bow",
        "Blind's Hideout - Left": "Reserve Tank",
        "Blind's Hideout - Right": "Energy Tank",
        "Blind's Hideout - Far Left": "Missile",
        "Blind's Hideout - Far Right": "Energy Tank",
        "Pegasus Rocks": "Piece Of Heart",
        "Bottle Merchant": "Twenty Rupees",
        "Magic Bat": "Heart Container",
        "Sick Kid": "Fifty Rupees",
        "Lost Woods Hideout": "Three Hundred Rupees",
        "Lumberjack Tree": "Missile",
        "Graveyard Ledge": "Missile",
        "Mushroom": "Energy Tank",
        "Floodgate Chest": "Super Missile",
        "Link's House": "Missile",
        "Aginah's Cave": "Missile",
        "Mini Moldorm Cave - Far Left": "Missile",
        "Mini Moldorm Cave - Left": "Power Bomb",
        "Mini Moldorm Cave - Right": "Progressive Armor",
        "Mini Moldorm Cave - Far Right": "Missile",
        "Ice Rod Cave": "Super Missile",
        "Hobo": "Heart Container",
        "Bombos Tablet": "Piece Of Heart",
        "Cave 45": "Twenty Rupees",
        "Checkerboard Cave": "Three Bombs",
        "Mini Moldorm Cave - NPC": "Twenty Rupees",
        "Library": "Twenty Rupees",
        "Maze Race": "Missile",
        "Desert Ledge": "Five Rupees",
        "Lake Hylia Island": "Progressive Armor",
        "Sunken Treasure": "Progressive Glove",
        "Flute Spot": "Three Hundred Rupees"
    },
    "Hyrule Castle": {
        "Sanctuary": "Bomb Upgrade (+10)",
        "Sewers - Secret Room - Left": "Sewers Key",
        "Sewers - Secret Room - Middle": "Heart Container",
        "Sewers - Secret Room - Right": "Missile",
        "Sewers - Dark Cross": "Sewers Map",
        "Hyrule Castle - Boomerang Chest": "Missile",
        "Hyrule Castle - Map Chest": "Book Of Mudora",
        "Hyrule Castle - Zelda's Cell": "Missile",
        "Link's Uncle": "Twenty Rupees",
        "Secret Passage": "Progressive Sword"
    },
    "Eastern Palace": {
        "Eastern Palace - Compass Chest": "Piece Of Heart",
        "Eastern Palace - Big Chest": "Eastern Palace Compass",
        "Eastern Palace - Cannonball Chest": "Eastern Palace Map",
        "Eastern Palace - Big Key Chest": "Eastern Palace Big Key",
        "Eastern Palace - Map Chest": "Energy Tank",
        "Eastern Palace - Armos Knights": "Progressive Shield",
        "Eastern Palace - Prize": "Crystal 2"
    },
    "Desert Palace": {
        "Desert Palace - Big Chest": "Desert Palace Map",
        "Desert Palace - Map Chest": "Desert Palace Key",
        "Desert Palace - Torch": "Piece Of Heart",
        "Desert Palace - Big Key Chest": "Desert Palace Big Key",
        "Desert Palace - Compass Chest": "Desert Palace Compass",
        "Desert Palace - Lanmolas'": "Heart Container",
        "Desert Palace - Prize": "Crystal 1"
    },
    "Death Mountain": {
        "Old Man": "Missile",
        "Spectacle Rock Cave": "Twenty Rupees",
        "Ether Tablet": "Missile",
        "Spectacle Rock": "Three Hundred Rupees",
        "Spiral Cave": "Super Missile",
        "Mimic Cave": "Half Magic",
        "Paradox Cave Lower - Far Left": "Bomb Upgrade (+5)",
        "Paradox Cave Lower - Left": "Progressive Glove",
        "Paradox Cave Lower - Right": "Twenty Rupees",
        "Paradox Cave Lower - Far Right": "Progressive Sword",
        "Paradox Cave Lower - Middle": "Piece Of Heart",
        "Paradox Cave Upper - Left": "Twenty Rupees",
        "Paradox Cave Upper - Right": "Missile",
        "Floating Island": "Energy Tank"
    },
    "Tower Of Hera": {
        "Tower of Hera - Big Key Chest": "Tower of Hera Key",
        "Tower of Hera - Basement Cage": "Tower of Hera Big Key",
        "Tower of Hera - Map Chest": "Tower of Hera Compass",
        "Tower of Hera - Compass Chest": "Missile",
        "Tower of Hera - Big Chest": "Tower of Hera Map",
        "Tower of Hera - Moldorm": "Piece Of Heart",
        "Tower of Hera - Prize": "Crystal 3"
    },
    "Castle Tower": {
        "Castle Tower - Room 03": "Agahnims Tower Key",
        "Castle Tower - Dark Maze": "Agahnims Tower Key"
    },
    "Dark World": {
        "Superbunny Cave - Top": "Twenty Rupees",
        "Superbunny Cave - Bottom": "Twenty Rupees",
        "Hookshot Cave - Top Right": "Super Missile",
        "Hookshot Cave - Top Left": "Twenty Rupees",
        "Hookshot Cave - Bottom Left": "Bug Catching Net",
        "Hookshot Cave - Bottom Right": "Missile",
        "Spike Cave": "Bombos",
        "Catfish": "Twenty Rupees",
        "Pyramid": "Energy Tank",
        "Pyramid Fairy - Left": "Ten Bombs",
        "Pyramid Fairy - Right": "Piece Of Heart",
        "Brewery": "Super Missile",
        "C-Shaped House": "Three Bombs",
        "Chest Game": "Three Bombs",
        "Hammer Pegs": "Missile",
        "Bumper Cave": "Ten Arrows",
        "Blacksmith": "Quake",
        "Purple Chest": "Fifty Rupees",
        "Hype Cave - Top": "Magical Boomerang",
        "Hype Cave - Middle Right": "Energy Tank",
        "Hype Cave - Middle Left": "Spazer",
        "Hype Cave - Bottom": "Missile",
        "Stumpy": "Ice Rod",
        "Hype Cave - NPC": "Piece Of Heart",
        "Digging Game": "Twenty Rupees",
        "Mire Shed - Left": "Missile",
        "Mire Shed - Right": "Progressive Sword"
    },
    "Dark Palace": {
        "Palace of Darkness - Shooter Room": "Palace of Darkness Big Key",
        "Palace of Darkness - Big Key Chest": "Palace of Darkness Key",
        "Palace of Darkness - The Arena - Ledge": "Palace of Darkness Key",
        "Palace of Darkness - The Arena - Bridge": "Palace of Darkness Key",
        "Palace of Darkness - Stalfos Basement": "Palace of Darkness Key",
        "Palace of Darkness - Map Chest": "Missile",
        "Palace of Darkness - Big Chest": "Bomb Upgrade (+5)",
        "Palace of Darkness - Compass Chest": "Palace of Darkness Key",
        "Palace of Darkness - Harmless Hellway": "Palace of Darkness Key",
        "Palace of Darkness - Dark Basement - Left": "Twenty Rupees",
        "Palace of Darkness - Dark Basement - Right": "Palace of Darkness Compass",
        "Palace of Darkness - Dark Maze - Top": "Missile",
        "Palace of Darkness - Dark Maze - Bottom": "Twenty Rupees",
        "Palace of Darkness - Helmasaur King": "Palace of Darkness Map",
        "Palace of Darkness - Prize": "Crystal 7"
    },
    "Swamp Palace": {
        "Swamp Palace - Entrance": "Swamp Palace Key",
        "Swamp Palace - Big Chest": "Twenty Rupees",
        "Swamp Palace - Big Key Chest": "Three Bombs",
        "Swamp Palace - Map Chest": "Super Missile",
        "Swamp Palace - West Chest": "Super Missile",
        "Swamp Palace - Compass Chest": "Hookshot",
        "Swamp Palace - Flooded Room - Left": "Energy Tank",
        "Swamp Palace - Flooded Room - Right": "Swamp Palace Big Key",
        "Swamp Palace - Waterfall Room": "Swamp Palace Compass",
        "Swamp Palace - Arrghus": "Swamp Palace Map",
        "Swamp Palace - Prize": "Crystal 5"
    },
    "Skull Woods": {
        "Skull Woods - Big Chest": "Skull Woods Map",
        "Skull Woods - Big Key Chest": "Skull Woods Compass",
        "Skull Woods - Compass Chest": "Skull Woods Big Key",
        "Skull Woods - Map Chest": "Skull Woods Key",
        "Skull Woods - Bridge Room": "Power Bomb",
        "Skull Woods - Pot Prison": "Skull Woods Key",
        "Skull Woods - Pinball Room": "Skull Woods Key",
        "Skull Woods - Mothula": "Cane Of Byrna",
        "Skull Woods - Prize": "Pendant Of Courage"
    },
    "Thieves Town": {
        "Thieves' Town - Attic": "Power Bomb",
        "Thieves' Town - Big Key Chest": "Thieves Town Big Key",
        "Thieves' Town - Map Chest": "Heart Container",
        "Thieves' Town - Compass Chest": "Thieves Town Compass",
        "Thieves' Town - Ambush Chest": "Thieves Town Map",
        "Thieves' Town - Big Chest": "Thieves Town Key",
        "Thieves' Town - Blind's Cell": "Fifty Rupees",
        "Thieves' Town - Blind": "Speed Booster",
        "Thieves' Town - Prize": "Crystal 4"
    },
    "Ice Palace": {
        "Ice Palace - Big Key Chest": "Ice Palace Compass",
        "Ice Palace - Compass Chest": "Ether",
        "Ice Palace - Map Chest": "Magic Powder",
        "Ice Palace - Spike Room": "Ice Palace Key",
        "Ice Palace - Freezor Chest": "Ice Palace Map",
        "Ice Palace - Iced T Room": "Ice Palace Big Key",
        "Ice Palace - Big Chest": "Ice Palace Key",
        "Ice Palace - Kholdstare": "Bottle (Blue Potion)",
        "Ice Palace - Prize": "Crystal 6"
    },
    "Misery Mire": {
        "Misery Mire - Big Chest": "Misery Mire Key",
        "Misery Mire - Main Lobby": "Misery Mire Key",
        "Misery Mire - Big Key Chest": "Misery Mire Compass",
        "Misery Mire - Compass Chest": "Bomb Upgrade (+5)",
        "Misery Mire - Bridge Chest": "Misery Mire Big Key",
        "Misery Mire - Map Chest": "Misery Mire Map",
        "Misery Mire - Spike Chest": "Misery Mire Key",
        "Misery Mire - Vitreous": "Super Missile",
        "Misery Mire - Prize": "Pendant Of Power"
    },
    "Turtle Rock": {
        "Turtle Rock - Chain Chomps": "Turtle Rock Key",
        "Turtle Rock - Compass Chest": "Turtle Rock Key",
        "Turtle Rock - Roller Room - Left": "Three Bombs",
        "Turtle Rock - Roller Room - Right": "Gravity Suit",
        "Turtle Rock - Big Chest": "Turtle Rock Key",
        "Turtle Rock - Big Key Chest": "Turtle Rock Big Key",
        "Turtle Rock - Crystaroller Room": "Arrow Upgrade (+5)",
        "Turtle Rock - Eye Bridge - Bottom Left": "Turtle Rock Compass",
        "Turtle Rock - Eye Bridge - Bottom Right": "Turtle Rock Map",
        "Turtle Rock - Eye Bridge - Top Left": "Turtle Rock Key",
        "Turtle Rock - Eye Bridge - Top Right": "Progressive Sword",
        "Turtle Rock - Trinexx": "Super Missile",
        "Turtle Rock - Prize": "Pendant Of Wisdom"
    },
    "Ganons Tower": {
        "Ganon's Tower - Bob's Torch": "Power Bomb",
        "Ganon's Tower - DMs Room - Top Left": "Ganons Tower Key",
        "Ganon's Tower - DMs Room - Top Right": "Reserve Tank",
        "Ganon's Tower - DMs Room - Bottom Left": "One Rupee",
        "Ganon's Tower - DMs Room - Bottom Right": "Piece Of Heart",
        "Ganon's Tower - Randomizer Room - Top Left": "Missile",
        "Ganon's Tower - Randomizer Room - Top Right": "Five Rupees",
        "Ganon's Tower - Randomizer Room - Bottom Left": "Arrow Upgrade (+5)",
        "Ganon's Tower - Randomizer Room - Bottom Right": "Piece Of Heart",
        "Ganon's Tower - Firesnake Room": "Ganons Tower Key",
        "Ganon's Tower - Map Chest": "Twenty Rupees",
        "Ganon's Tower - Big Chest": "Ganons Tower Compass",
        "Ganon's Tower - Hope Room - Left": "Super Missile",
        "Ganon's Tower - Hope Room - Right": "Twenty Rupees",
        "Ganon's Tower - Bob's Chest": "Three Bombs",
        "Ganon's Tower - Tile Room": "Ganons Tower Key",
        "Ganon's Tower - Compass Room - Top Left": "Missile",
        "Ganon's Tower - Compass Room - Top Right": "Super Missile",
        "Ganon's Tower - Compass Room - Bottom Left": "Heart Container",
        "Ganon's Tower - Compass Room - Bottom Right": "Plasma Beam",
        "Ganon's Tower - Big Key Chest": "Ganons Tower Big Key",
        "Ganon's Tower - Big Key Room - Left": "Reserve Tank",
        "Ganon's Tower - Big Key Room - Right": "Shovel",
        "Ganon's Tower - Mini Helmasaur Room - Left": "Arrow Upgrade (+5)",
        "Ganon's Tower - Mini Helmasaur Room - Right": "Ganons Tower Key",
        "Ganon's Tower - Pre-Moldorm Chest": "Ganons Tower Map",
        "Ganon's Tower - Moldorm Chest": "Piece Of Heart"
    },
    "Special": {
        "Turtle Rock Medallion": "Quake",
        "Misery Mire Medallion": "Bombos",
        "Waterfall Bottle": "Bottle (Green Potion)",
        "Pyramid Bottle": "Bottle (Blue Potion)"
    },
    "Crateria": {
        "Power Bomb (Crateria surface)": "Super Missile",
        "Missile (Crateria middle)": "Fire Rod",
        "Missile (Crateria bottom)": "Energy Tank",
        "Super Missile (Crateria)": "Bomb Upgrade (+5)",
        "Bombs": "Super Missile",
        "Energy Tank, Terminator": "Missile",
        "Energy Tank, Gauntlet": "Power Bomb",
        "Missile (Crateria gauntlet right)": "Morph Bombs",
        "Missile (Crateria gauntlet left)": "Super Missile",
        "Missile (outside Wrecked Ship bottom)": "Power Bomb",
        "Missile (outside Wrecked Ship top)": "Magic Mirror",
        "Missile (outside Wrecked Ship middle)": "Bomb Upgrade (+5)",
        "Missile (Crateria moat)": "Power Bomb"
    },
    "Brinstar": {
        "Power Bomb (green Brinstar bottom)": "Flute",
        "Missile (green Brinstar below super missile)": "Super Missile",
        "Super Missile (green Brinstar top)": "Power Bomb",
        "Reserve Tank, Brinstar": "Arrow Upgrade (+5)",
        "Missile (green Brinstar behind missile)": "Cane Of Somaria",
        "Missile (green Brinstar behind reserve tank)": "Energy Tank",
        "Energy Tank, Etecoons": "Missile",
        "Super Missile (green Brinstar bottom)": "One Rupee",
        "Super Missile (pink Brinstar)": "Fifty Rupees",
        "Missile (pink Brinstar top)": "Pegasus Boots",
        "Missile (pink Brinstar bottom)": "Missile",
        "Charge Beam": "One Hundred Rupees",
        "Power Bomb (pink Brinstar)": "Piece Of Heart",
        "Missile (green Brinstar pipe)": "Bottle (Golden Bee)",
        "Energy Tank, Waterway": "Ten Arrows",
        "Energy Tank, Brinstar Gate": "Energy Tank",
        "Morphing Ball": "Piece Of Heart",
        "Power Bomb (blue Brinstar)": "Missile",
        "Missile (blue Brinstar middle)": "Three Bombs",
        "Energy Tank, Brinstar Ceiling": "Super Missile",
        "Missile (blue Brinstar bottom)": "Missile",
        "Missile (blue Brinstar top)": "Hammer",
        "Missile (blue Brinstar behind missile)": "Missile",
        "X-Ray Scope": "Heart Container",
        "Power Bomb (red Brinstar sidehopper room)": "Bottle (Blue Potion)",
        "Power Bomb (red Brinstar spike room)": "Three Hundred Rupees",
        "Missile (red Brinstar spike room)": "Piece Of Heart",
        "Spazer": "Twenty Rupees",
        "Energy Tank, Kraid": "Piece Of Heart",
        "Varia Suit": "Sancturary Heart Container",
        "Missile (Kraid)": "Piece Of Heart"
    },
    "Norfair": {
        "Ice Beam": "Missile",
        "Missile (below Ice Beam)": "Missile",
        "Hi-Jump Boots": "Twenty Rupees",
        "Missile (Hi-Jump Boots)": "Fifty Rupees",
        "Energy Tank (Hi-Jump Boots)": "Five Rupees",
        "Missile (lava room)": "Wave Beam",
        "Reserve Tank, Norfair": "Twenty Rupees",
        "Missile (Norfair Reserve Tank)": "Twenty Rupees",
        "Missile (bubble Norfair green door)": "Screw Attack",
        "Missile (bubble Norfair)": "Twenty Rupees",
        "Missile (Speed Booster)": "Ice Beam",
        "Speed Booster": "Fifty Rupees",
        "Missile (Wave Beam)": "Twenty Rupees",
        "Wave Beam": "Arrow Upgrade (+5)",
        "Energy Tank, Crocomire": "Fifty Rupees",
        "Missile (above Crocomire)": "Piece Of Heart",
        "Power Bomb (Crocomire)": "Missile",
        "Missile (below Crocomire)": "Silver Arrows Upgrade",
        "Missile (Grapple Beam)": "Missile",
        "Grapple Beam": "Energy Tank"
    },
    "Lower Norfair": {
        "Missile (Gold Torizo)": "Three Hundred Rupees",
        "Super Missile (Gold Torizo)": "Bomb Upgrade (+5)",
        "Screw Attack": "Piece Of Heart",
        "Missile (Mickey Mouse room)": "Spring Ball",
        "Missile (lower Norfair above fire flea room)": "Magic Cape",
        "Power Bomb (lower Norfair above fire flea room)": "Power Bomb",
        "Power Bomb (Power Bombs of shame)": "Missile",
        "Missile (lower Norfair near Wave Beam)": "Arrow Upgrade (+10)",
        "Energy Tank, Ridley": "Bottle (Green Potion)",
        "Energy Tank, Firefleas": "Piece Of Heart"
    },
    "Wrecked Ship": {
        "Missile (Wrecked Ship middle)": "Arrow Upgrade (+5)",
        "Reserve Tank, Wrecked Ship": "Blue Boomerang",
        "Missile (Gravity Suit)": "Heart Container",
        "Missile (Wrecked Ship top)": "Missile",
        "Energy Tank, Wrecked Ship": "X-Ray Scope",
        "Super Missile (Wrecked Ship left)": "Ten Arrows",
        "Right Super, Wrecked Ship": "Missile",
        "Gravity Suit": "Charge Beam"
    },
    "Maridia": {
        "Missile (green Maridia shinespark)": "Single Arrow",
        "Super Missile (green Maridia)": "Piece Of Heart",
        "Energy Tank, Mama turtle": "Hi-Jump Boots",
        "Missile (green Maridia tatori)": "Varia Suit",
        "Super Missile (yellow Maridia)": "Space Jump",
        "Missile (yellow Maridia super missile)": "Energy Tank",
        "Missile (yellow Maridia false wall)": "Lamp",
        "Plasma Beam": "Progressive Shield",
        "Missile (left Maridia sand pit room)": "Piece Of Heart",
        "Reserve Tank, Maridia": "Twenty Rupees",
        "Missile (right Maridia sand pit room)": "Missile",
        "Power Bomb (right Maridia sand pit room)": "Heart Container",
        "Missile (pink Maridia)": "Flippers",
        "Super Missile (pink Maridia)": "Energy Tank",
        "Spring Ball": "Twenty Rupees",
        "Missile (Draygon)": "Reserve Tank",
        "Energy Tank, Botwoon": "Three Bombs",
        "Space Jump": "Missile"
    },
    "Tourian": []
"playthrough": {
        "1": {
            "Light World": {
                "Sahasrahla's Hut - Middle": "Power Bomb",
                "Chicken House": "Moon Pearl",
                "Blind's Hideout - Top": "Bow",
                "Blind's Hideout - Far Right": "Energy Tank",
                "Mushroom": "Energy Tank",
                "Mini Moldorm Cave - Left": "Power Bomb",
                "Ice Rod Cave": "Super Missile",
                "Sunken Treasure": "Progressive Glove"
            },
            "Hyrule Castle": {
                "Hyrule Castle - Map Chest": "Book Of Mudora",
                "Secret Passage": "Progressive Sword"
            },
            "Eastern Palace": {
                "Eastern Palace - Map Chest": "Energy Tank"
            }
        },
        "2": {
            "Light World": {
                "King Zora": "Mushroom"
            }
        },
        "3": {
            "Light World": {
                "Potion Shop": "Morphing Ball"
            },
            "Desert Palace": {
                "Desert Palace - Big Key Chest": "Desert Palace Big Key"
            }
        },
        "4": {
            "Crateria": {
                "Missile (Crateria middle)": "Fire Rod"
            },
            "Brinstar": {
                "Power Bomb (green Brinstar bottom)": "Flute",
                "Missile (blue Brinstar top)": "Hammer",
                "Kraid": "Defeat Kraid"
            }
        },
        "5": {
            "Desert Palace": {
                "Desert Palace - Prize": "Crystal 1"
            },
            "Dark Palace": {
                "Palace of Darkness - Shooter Room": "Palace of Darkness Big Key"
            },
            "Thieves Town": {
                "Thieves' Town - Big Key Chest": "Thieves Town Big Key"
            }
        },
        "6": {
            "Thieves Town": {
                "Thieves' Town - Blind": "Speed Booster",
                "Thieves' Town - Prize": "Crystal 4"
            }
        },
        "7": {
            "Crateria": {
                "Missile (Crateria gauntlet right)": "Morph Bombs",
                "Missile (outside Wrecked Ship top)": "Magic Mirror"
            },
            "Brinstar": {
                "Missile (green Brinstar behind missile)": "Cane Of Somaria"
            },
            "Wrecked Ship": {
                "Gravity Suit": "Charge Beam",
                "Phantoon": "Defeat Phantoon"
            }
        },
        "8": {
            "Death Mountain": {
                "Paradox Cave Lower - Left": "Progressive Glove",
                "Paradox Cave Lower - Far Right": "Progressive Sword"
            },
            "Tower Of Hera": {
                "Tower of Hera - Basement Cage": "Tower of Hera Big Key"
            }
        },
        "9": {
            "Tower Of Hera": {
                "Tower of Hera - Prize": "Crystal 3"
            },
            "Dark World": {
                "Blacksmith": "Quake"
            }
        },
        "10": {
            "Turtle Rock": {
                "Turtle Rock - Roller Room - Right": "Gravity Suit"
            }
        },
        "11": {
            "Maridia": {
                "Missile (green Maridia tatori)": "Varia Suit",
                "Missile (yellow Maridia false wall)": "Lamp",
                "Missile (pink Maridia)": "Flippers",
                "Draygon": "Defeat Draygon"
            }
        },
        "12": {
            "Eastern Palace": {
                "Eastern Palace - Big Key Chest": "Eastern Palace Big Key"
            },
            "Dark Palace": {
                "Palace of Darkness - Prize": "Crystal 7"
            },
            "Ice Palace": {
                "Ice Palace - Iced T Room": "Ice Palace Big Key"
            },
            "Lower Norfair": {
                "Ridley": "Defeat Ridley"
            }
        },
        "13": {
            "Eastern Palace": {
                "Eastern Palace - Prize": "Crystal 2"
            },
            "Swamp Palace": {
                "Swamp Palace - Compass Chest": "Hookshot"
            },
            "Tourian": {
                "Mother Brain": "Defeat Mother Brain"
            }
        },
        "14": {
            "Swamp Palace": {
                "Swamp Palace - Prize": "Crystal 5"
            },
            "Ice Palace": {
                "Ice Palace - Prize": "Crystal 6"
            }
        },
        "15": {
            "Ganons Tower": {
                "Ganon's Tower - Big Key Chest": "Ganons Tower Big Key"
            }
        },
        "16": {
            "Ganons Tower": {
                "Agahnim 2": "Defeat Agahnim 2"
            }
        },
        "17": {
            "Dark World": {
                "Ganon": "Triforce"
            }
        },
        "longest_item_chain": 17,
        "regions_visited": 33
    },
}

**Comment by drb647** [comment]
The invisible bridge in blue Brinstar doesn't require any additional upgrades to cross.  If you fell into the water before the bridge, shoot the door open and walljump into it when the water is at its lowest point.  To get onto the bridge, get a short running start in the previous room where you came up through the ceiling, jump (and hold jump) just before passing through the door and you should land on the bridge.  If you have a good handle on where the bridge ends you can also walljump up off the end if you come up short.  

I believe that Walljump into Kraid is fair game in logic.  

Neither of these are terribly difficult with a bit of practice.  Note for both: turn Speed Booster off if you have it without Hi-Jump as it lowers your jump arcs.

**Comment by DJTeeJay80** [comment]
Thank you for the hint, I did it! I couldn't reach the edge for walljumping into Kraid's lair, but with the hammer I was able to get the Speed Booster from Blind. With this I got access to the Crateria Gauntlet where the Morph Bomb ability was hidden so I got into Kraid's lair by bombjumping.

I don't have much of practice in Super Metroid; I've played the original game only once, and it's my first Combo-Randomizer-Seed. O:-)

**Comment by drb647** [comment]
The Kraid walljump takes practice, but once you get it right a few times it becomes second nature.  Start on the one-block step, hold run and right for a split second before you jump, don't release jump until you reach the ledge, and keep in mind that you don't have to be flush against the ledge to get the wall jump; there's a couple pixels worth of leeway.
