### ISSUE TITLE
Save memory not initialized

### ISSUE THREAD

**Issue by Kreeblah** [tewtal/alttp_sm_combo_randomizer#141]
Console or Emulator: Console

Description of problem: Per https://github.com/MiSTer-devel/SNES_MiSTer/issues/175#issuecomment-571666141, the ROM doesn't initialize save memory before attempting to read from it.  On real hardware, this is full of random values, but many emulators (and the SD2SNES) pre-fill it with FF.  This is also likely related to https://github.com/tewtal/alttp_sm_combo_randomizer/issues/5.

**Comment by tewtal** [comment]
This should be fixed with [this commit](https://github.com/tewtal/alttp_sm_combo_randomizer_rom/commit/2462d3c0f7c194d7bd31ec581eb2d03ac0adce0a), and the V11 beta site should already be updated with the fix.
Thanks for reporting.
