### ISSUE TITLE
Ganon's Tower torch item inherits graphic from big chest item

### ISSUE THREAD

**Issue by KevinMoonglow** [tewtal/alttp_sm_combo_randomizer#16]
Console or Emulator: Emulator

 If emulator state which emulator and version.
RetroArch 1.7.3 - Snes9x Core 1.54.1

Original Filename: 
SMALttP - sm-casual_alttp-no-glitches-v9.1_normal-open_swords-randomized_morph-randomized_ganon_combo_272910813.sfc

Seed: 272910813

Item, Entrance or Custom: 

Mode: Randomized Swords, Randomized Morph
Logic: No Glitches, Casual
Goal: Defeat Ganon and Mother Brain
Difficulty: Normal
Variation: ALTTP+SM Combo Randomizer

Description of problem: Ice Beam is on Ganon's Tower Torch, and looks normal when first seen, but appears to morph into Super Missiles immediately after the Supers are collected from the Big Chest.
The morphed Ice Beam looks like Supers, but with Ice Beam palette, and morphs back into Ice Beam when collected. The item behaves like a normal Ice Beam.

Spoiler (if available):
[SMALttP - sm-casual_alttp-no-glitches-v9.1_normal-open_swords-randomized_morph-randomized_ganon_combo_272910813.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2041459/SMALttP.-.sm-casual_alttp-no-glitches-v9.1_normal-open_swords-randomized_morph-randomized_ganon_combo_272910813.txt)

This is a RetroArch savestate just before opening the big chest, but with Boots collected. If you ignore the chest and move north, you'll see Ice Beam. If you open the chest, then move north, you'll see miscolored Supers. Collecting the miscolored supers morphs them back into Ice Beam.
[state.zip](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2041463/state.zip)

**Comment by SmolBig** [comment]
This sounds similar to the Zora ledge item glitch that Karkat fixed in LttPR recently. I'm interested to know if this is an LttPR bug or if it's unique to LttSM.

**Comment by tewtal** [comment]
A fix for this issue will be in V10, thanks for reporting this.
