### ISSUE TITLE
Dungeon 2 can be softlocked by small keys

### ISSUE THREAD

**Issue by Bioniclegenius** [tewtal/alttp_sm_combo_randomizer#19]
Console or Emulator:

 Emulator, Snes9X v1.54

Original Filename:

SMALttP - sm-casual_alttp-no-glitches-v9.1_normal-open_swords-randomized_morph-randomized_ganon_combo_307925591.sfc

Item, Entrance or Custom: 

Dungeon 2 of Dark World

Mode: Casual
Logic: No glitches
Goal: Both endings
Difficulty: Casual
Variation: 

Description of problem:

It's possible to run out of small keys in this dungeon. At the beginning, there is a small key under a pot that can be flooded by the lever to the left. Once flooded, it never un-floods, even after rebooting the game or savequitting or hopping to SM and back.

Screenshot of issue: https://puu.sh/AuKhf/7f29e01a41.png

**Comment by lenophis** [comment]
LttP logic will let you unflood it, but you must leave the Swamp Palace map area and come back. If you have to reopen the floodgates in the Light World, then it should be open again.

**Comment by tewtal** [comment]
Closing this since it has been answered and unflooding the key is the solution to this issue.
