### ISSUE TITLE
Hyrule Sewer key locked behind door

### ISSUE THREAD

**Issue by birbbrain** [tewtal/alttp_sm_combo_randomizer#26]
Console or Emulator:
Emulator

 If emulator state which emulator and version.
higan v106

Original Filename:
SMALttP - valttp-no-glitches-v9.2_normal-open-randomized-ganon_combo_88835400.sfc

Seed:
88835400.

Item, Entrance or Custom: 
Hyrule Sewer small key door

Mode: Casual
Logic: No glitches
Goal: Both
Difficulty: Casual
Variation: 

Description of problem:
Small key for Hyrule Sewers locked behind door, locking out Cane of Somaria.

Spoiler (if available):
[SMALttP - valttp-no-glitches-v9.2_normal-open-randomized-ganon_combo_88835400.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2065803/SMALttP.-.valttp-no-glitches-v9.2_normal-open-randomized-ganon_combo_88835400.txt)

"Hyrule Castle": {
        "Sanctuary": "Sewers Map",
        "Sewers - Secret Room - Left": "Cane Of Somaria",
        "Sewers - Secret Room - Middle": "Energy Tank",
        "Sewers - Secret Room - Right": "Sewers Key",
        "Sewers - Dark Cross": "Bow",
        "Hyrule Castle - Boomerang Chest": "Twenty Rupees",
        "Hyrule Castle - Map Chest": "Ice Rod",
        "Hyrule Castle - Zelda's Cell": "Energy Tank",
        "Link's Uncle": "Fifty Rupees",
        "Secret Passage": "Missile"
    },

**Comment by gjgfuj** [comment]
You can drop down from above via the secret entrance in the graveyard. you have the glove to do so.
