### ISSUE TITLE
Unable to open on SNES Classic

### ISSUE THREAD

**Issue by mrmatt3465** [tewtal/alttp_sm_combo_randomizer#28]
Console or Emulator: SNES Classic

Description of problem:

I am able to create the rom using the website but I am unable to boot it after adding it to my SNES classic using Hakchi2. I have tried running it using the native emulator (canoe?), as well as retroarch cores SNES9x2010 and BSNES and I get a black screen upon loading the rom. Is there a specific retroarch core or another way to get this to work on the SNES Classic?

**Comment by Josephur** [comment]
Did you try Snes9x version 1.55?

**Comment by mrmatt3465** [comment]
I have also tried the SNES9X version 1.55 retroarch core. When I boot the game all I get is a black screen. If I boot the game on a computer, I get a bad checksum but the game still plays [on SNES9X 1.55 as well]. Do I need to repair the bad checksum for it to boot properly on the SNES Classic?

**Comment by mrmatt3465** [comment]
I just got it to work! For anyone with a similar issue here is what I did: reloaded the hakchi2 kernel, reinstalled retroarch, reinstalled SNES9x core, added the ROM uncompressed to the SNES using hakchi2. Works like a charm now.
