### ISSUE TITLE
Item Randomization needs a little work

### ISSUE THREAD

**Issue by DaletheCharmeleon** [tewtal/alttp_sm_combo_randomizer#30]
Console or Emulator: SNES9XGX (SNES Wii Emulator)

 If emulator state which emulator and version. 4.3.2

Original Filename: First time ALTTP SM Crossover_127747304

Seed: 127747304

Item, Entrance or Custom: Item

Mode: Open
Logic: No Glitches
Goal: Defeat Ganon/Mother Brain
Difficulty: Normal
Variation: Combo

Description of problem:

Two specific items needed for progression got randomized into inaccessable areas for my point of the game. One is the Flute, which got placed in Maridia, behind some Speed Booster blocks, along with the Bombs. The other item is the Book of Mudora, which is Ganon's Tower, unaccessable until I have all Crystals. My problem is that the Speed Booster is in the Desert Palace which can only be accessed by use of either of these items, as well as one of the Crystals to access Ganon's Tower. If there is a way around this issue, I would not mind the help, but as of right now, I have a dead game. Sorry, but I needed to address this.

Spoiler (if available):

**Comment by drb647** [comment]
Where in Maridia was the flute?  Inner Maridia can be accessed through ALttP by the Dark World Ice Rod cave, allowing access to Draygon and Botwoon's pickups without speed booster.  The only pickup in Maridia that's speed booster locked is Main Street.

**Comment by DaletheCharmeleon** [comment]
It is two rooms before Botwoon, the big 'hub' area in the very center of Maridia, where those snail enemies mostly hang out.

**Comment by drb647** [comment]
Hmm... can you get to Lower Norfair?  The energy charge station will take you to Misery Mire without needing the flute, then mirror into Desert Palace.  Need Space Jump, Varia, Gravity and power bombs in casual SM logic.

**Comment by DaletheCharmeleon** [comment]
Ah. I was not aware of the warp directly to Misery Mire. Okay. That makes me feel better. Thank you!

Maybe, for a Spoiler section, if ever useless entrances/caves are randomized, add where one entrance will warp you in between games? Just a suggestion so people like me won't get lost.
