### ISSUE TITLE
Shovel picked up, but not in inventory

### ISSUE THREAD

**Issue by Josephur** [tewtal/alttp_sm_combo_randomizer#38]
Console or Emulator: snes9x 1.56.1
smalttp version: 9.2

Original Filename: SMALttP - sm-casual_alttp-no-glitches-v9.2_normal-open_morph-vanilla_ganon_combo_256990202.sfc

Seed:  256990202

Mode/Logic/Goal/Difficulty/Variation: Casual, no glitches, normal, open_morph vanilla ganon_combo

Description of problem: Picked up shovel item in SM, however it's not inventory once I warp over to alttp

Spoiler (if available):
Super Missile (pink Brinstar) | Shovel

Snes9x state file attached for verification purposes.
[SMALttP - sm-casual_alttp-no-glitches-v9.2_normal-open_morph-vanilla_ganon_combo_256990202.zip](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2098958/SMALttP.-.sm-casual_alttp-no-glitches-v9.2_normal-open_morph-vanilla_ganon_combo_256990202.zip)

**Comment by Josephur** [comment]
Note, I just now double verified this by reloading this state, grabbing shovel again, and then warping to alttp, shovel still missing in inventory.

<img width="1869" alt="2018-06-13 1" src="https://user-images.githubusercontent.com/6666442/41371690-28ddb676-6f19-11e8-9c0b-d87ae7bb271f.png">

<img width="1919" alt="2018-06-13 2" src="https://user-images.githubusercontent.com/6666442/41371695-2d1eef66-6f19-11e8-9a23-af6ed929163c.png">

I guess this seed is bunk, will try a new one.

**Comment by drb647** [comment]
Press Y while the cursor is on the flute.

**Comment by Josephur** [comment]
Wow, that easy huh?   Is that a specific feature of the randomizer, or was that in the original alltp?  I haven't played in a long time.  Anyways closing this "issue" as its a non-issue! lol

**Comment by drb647** [comment]
Specific to randomizer to allow use of the shovel if acquired after the flute.  Same deal for mushroom/powder, arrows and boomerangs.  Covered in the game documentation: https://docs.google.com/document/d/1fP-DRbuROuQ-zifwKftuV-Paoh0_GGYErLGv3VVAg7Y/

**Comment by Josephur** [comment]
It does help to RTFM :)
