### ISSUE TITLE
Gloves/Hammer Unobtainable?

### ISSUE THREAD

**Issue by Clyobate** [tewtal/alttp_sm_combo_randomizer#39]
Console or Emulator:
Snes9x 1.56.1
 If emulator state which emulator and version.

Original Filename:

Seed: 729132841

Item, Entrance or Custom: Item

Mode: Open
Logic: No Glitches, Casual
Goal: Ganon/Mother Brain
Difficulty: Normal
Variation: Combo Randomizer

Description of problem:
The "Progressive Gloves" are located in areas that seem inaccessible. One is through Bumper Cave, and the other is in the Map Chest in the Swamp Palace. I can't reach either of these, either because I don't have the glove or because I don't have the hammer, which is located at the Death Mountain floating island, which I can only reach with the ability to lift dark rocks, I believe. Any help is greatly appreciated, and thanks in advance!

Spoiler (if available):

**Comment by drb647** [comment]
Neither require hammer.  Try this:

Dark world via Aghinim (lamp + sword, maybe cape)
Cross the river (flippers + hookshot), pass the cemetary, get bumper cave.
Through Village of Outcasts to swamp (you just got L1 glove)

**Comment by drb647** [comment]
Oops - forgot the rock in front of bumper cave.  Still pretty much the same idea, should be able to get swamp palace map chest first without needing glove or hammer.

**Comment by Clyobate** [comment]
Just tried it; forgot I could hookshot to skulls. Thank you!
