### ISSUE TITLE
SD2SNES Crashes

### ISSUE THREAD

**Issue by miketrethewey** [tewtal/alttp_sm_combo_randomizer#40]
Submitted by Popplars to #bug-reports on the Discord.

Console or Emulator: SD2SNES v0.1.7e-USB-v7

<img src="https://cdn.discordapp.com/attachments/445949699023699970/457687749554602004/IMG_20180616_185447.jpg" width="300" /><img src="https://cdn.discordapp.com/attachments/445949699023699970/457687750053986334/IMG_20180616_184146.jpg" width="300" /><img src="https://cdn.discordapp.com/attachments/445949699023699970/457687750053986335/IMG_20180616_191719.jpg" width="300" /><img src="https://cdn.discordapp.com/attachments/445949699023699970/457687750926270484/IMG_20180616_185035.jpg" width="300" />

**Comment by miketrethewey** [comment]
Maniacal reports in #bug-reports on the Discord that a potential solution is to roll back the firmware from v0.1.7e to v0.1.7b.

**Comment by tewtal** [comment]
I had similar issues using the usb2snes-firmware and rolling back to stock 0.1.7e solved it for me. I'm not sure why it breaks with the USB firmware but when I get time I'll try to look into it.
