### ISSUE TITLE
Website Help

### ISSUE THREAD

**Issue by DerpyCoder21** [tewtal/alttp_sm_combo_randomizer#41]
hey so im using OpenEmu Also Im On A Mac. So When I Import The Super Metroid File It Rather Says Rom Wont Work OR it goes to a blank screen.

**Comment by Josephur** [comment]
Have  you tried bsnes or Snes9x for Mac?  I know certain emulators will not run the rom, but not that familiar with Mac emulators.

**Comment by sloanr333** [comment]
I think you're struggling with some emulator issues. I would suggest going to the support forum for the emulator itself and asking there, or maybe asking in the [Discord](https://discord.gg/9GyKNKt).
