### ISSUE TITLE
Mama Turtle Room E-Tank : Possible Minor tournament logic error?

### ISSUE THREAD

**Issue by MP2E** [tewtal/alttp_sm_combo_randomizer#42]
Hi there! I'm new to Super Metroid randomizers and might be missing something obvious here, but I think there's a small error in this line:

https://github.com/tewtal/alttp_sm_combo_randomizer/blob/e38e3c2c23a70a810012edee239e9affd2506f23/app/Region/SuperMetroid/Maridia/Outer.php#L60

Based off this, speedbooster is one of the possible required items for the E-tank, but speedbooster without gravity suit will not work. On line 56, the green Maridia shinespark missile tank has both Gravity and Speedbooster needed.

Perhaps there's some logic I'm missing that already implies that you have gravity suit for this room? I didn't see it for tournament logic. Casual logic does imply gravity suit, though.

**Comment by HorikawaOtane** [comment]
I will say - the tournament logic does allow you to get into this room without gravity suit. I’ve had to do it via mid air spring ball jumping to get progression. I’m not sure if there’s a trick I’m unaware of to activate speed booster above the water in that room somehow.

**Comment by sloanr333** [comment]
v10 has added Spring Ball as a requirement for that item, and as HorikawaOtane has noted that means it's not softlockable anymore.

[MaridiaMamaTurtle_92vs10.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2194579/MaridiaMamaTurtle_92vs10.txt)

**Comment by MP2E** [comment]
Awesome to hear!! Thanks!

**Comment by HorikawaOtane** [comment]
I BELIEVE what they want you to do is get a spike suit....

https://pastebin.com/qUaVXHpv

This seems ridiculous though, but I haven’t tried it yet. It could be easier than it sounds...

**Comment by HorikawaOtane** [comment]
Yeah, I think this is what they genuinely want you to do.

1) Go to http://deanyd.net/sm/index.php?title=List_of_Energy_Tanks#Norfair_3 to generate a spike suit
2) Make your way to Maridia and climb suitless to get to the turtle room (though this would require hi jump and ice shot or hi jump and grapple or hi jump and spring ball, no?) and somehow preserve your spikesuit the whole way.
3) Use the spike suit to get the item. Hope you don’t miss. Like this video (https://ia801207.us.archive.org/27/items/viptech/poorly%20spliced%20rbo%20fishtank%20spark%20idea.mp4), but in the turtle room.

**Comment by tewtal** [comment]
Wow, a lot of crazy assumptions here without actually doing in-game testing I see :)
Spike suit or blue suit is not and will not be a requirement in tournament logic.

All you have to do with HJ+Speed suitless is to ride the shell up, jump to the left wall where there's a little ledge, and from there just run and jump towards the item on the grapple block.
