### ISSUE TITLE
roms

### ISSUE THREAD

**Issue by DIOisgod** [tewtal/alttp_sm_combo_randomizer#44]
i try to upload the roms but they are not accepted btw on android and the roms are the ones wanted

**Comment by sloanr333** [comment]
I'm not exactly sure what you're getting at here, but I think you're struggling with some basic/general emulator issues. I would suggest going to the support forum for the emulator itself and asking there, or maybe asking in the [Discord](https://discord.gg/9GyKNKt). The github issues tracker is more for code-specific problems.

**Comment by SmolBig** [comment]
There's nothing about Android that would cause a problem. I can generate a rom from my Android browser (Chrome) with no issues.
