### ISSUE TITLE
Add Space Jump, Spring Ball, or Gravity Suit to Maridia Left Sand Pit Requirements

### ISSUE THREAD

**Issue by HorikawaOtane** [tewtal/alttp_sm_combo_randomizer#47]
Console or Emulator:

Emulator - Bsnes 106.44.

Original Filename:

sm_alttp - total_VT_sm-tournament_alttp-no-glitches-v9.2_normal_open_randomized_combo_882734794.sfc

Seed:

882734794

Item, Entrance or Custom: Item

Mode: Open
Logic: Tournament
Goal: Kill Ganon/MB
Difficulty: normal
Variation: combo

Description of problem:

It is borderline TAS-specific to get into the Maridia left sand pit suitless without space jump. I have been practicing this trick for almost 20 hours with no success. The only training videos that exist are intended for TAS-training and use slowdown to accomplish the task https://www.youtube.com/watch?v=1M2TiEVwH2I. To quote the cited training video - "of course I did the sand-bombjump with savestates and the walljump climb with slowdown"

While it is certainly POSSIBLE to complete by a human, as many TAS tricks are, the requirements are much higher than any other SM required trick the logic could ask of you and, I suspect, may require custom controllers or something of that sort.

Spoiler (if available):

[sm_alttp - total_VT_sm-tournament_alttp-no-glitches-v9.2_normal_open_randomized_combo_882734794.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2161830/sm_alttp.-.total_VT_sm-tournament_alttp-no-glitches-v9.2_normal_open_randomized_combo_882734794.txt)

![bsnes](https://user-images.githubusercontent.com/12112721/42256594-3c03486c-7f20-11e8-80c6-324e3a54913d.gif)

**Comment by HorikawaOtane** [comment]
Adding springball would also be fine - then you could simply mid-air springball jump up there.

**Comment by HorikawaOtane** [comment]
(As an additional side-note - even crossproduct's plando considers this technique, which is also not documented at all on crocomi.re, to be too difficult and does not include it)

**Comment by MP2E** [comment]
I have made a pull request to address this issue because I agree that doing this suitless with hijump alone is too difficult

**Comment by sloanr333** [comment]
Pretty cool MP2E! However, it looks like the v10 logic already has that change in the works. Specifically, all the sand pit rooms are getting a rework to need either high jump or gravity, and the right sand pit power bomb location needs either high jump and springball or just gravity.

**Comment by MP2E** [comment]
Thanks for letting me know! Guess my PR can be closed then 👍

**Comment by sloanr333** [comment]
As irony would have it, I just rolled a seed that requires suitless left pits. Can't for the life of me figure it out with only high jump. Looking again at the v10 logic I think I might have misread it! In fact the whole dang thread! The v10 logic does have spring ball for the RIGHT pits, but not for the left... The left is just gravity or high jump, which as both of us now know is probably the hardest trick in the logic if gravity is locked. Sorry for misunderstanding, but I think your pull request is still relevant...!

**Comment by HorikawaOtane** [comment]
I literally just rolled a seed that had the gravity suit up there.

Thankfully, I had spring ball - the mid air spring ball jump is extremely precise, but it IS doable. I would consider that reasonable for a human to perform.

**Comment by tewtal** [comment]
I've done some testing and considerations and I agree that just suitless high jump here might be a bit punishing in comparison to other required tricks. This will be changed to High Jump + Spring Ball or High Jump + Space Jump or Gravity.

**Comment by tewtal** [comment]
Fixed for V10
