### ISSUE TITLE
Website Rom Upload Order Issue

### ISSUE THREAD

**Issue by Aaron-Usher** [tewtal/alttp_sm_combo_randomizer#49]
Browser: Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)

Description of problem:

The website asks for you to provide your roms before you can use it. I first submitted a Link to the Past rom and then a Super Metroid rom and it had an error; one of the roms I provided clearly wasn't correct, either due to the wrong version of the Link to the Past rom or having the wrong header state on the Super Metroid rom. Thinking it was a problem with the Super Metroid rom, I then chose another rom. This caused the website to hang forever with the main screen being white. After this, I tried opening up new tabs and even a different browser (the current version of Firefox) to try and upload a correct Super Metroid rom, but it always caused it to hang forever. Eventually, I theorized that the problem was the lack of a Link to the Past rom, and that seems to be correct; after I uploaded that first, it gave out error messages (and eventually a randomizer) in no time. Is it dependant on A Link to the Past rom being uploaded first? If so, is there any reason that it should be like that and not just have a submit button or something?

Also, the website has nothing selected for the "Swords" option by default. However, now that I've selected "Randomized", I can't change it. Is not selecting anything intended to be an option? If so, why can't I change it back? If not, why does it default to nothing like that?

**Comment by tewtal** [comment]
There's a bug in v9.2 where uploading the SM ROM first will cause issues. This has been fixed for V10.

In regards to the randomized swords thing it's another bug in the web interface, but it doesn't currently cause an issues since it's by default randomized swords and that's the only valid choice right now.

I'll make sure it's fixed when more sword options are added into the randomizer.
