### ISSUE TITLE
Casual seed with tournament logic: 68299872

### ISSUE THREAD

**Issue by OmnerG** [tewtal/alttp_sm_combo_randomizer#50]
Emulator
Snes9X v1.55 for Windows.
Original Filename:
SMALttP - sm-casual_alttp-no-glitches-v9.2_normal-open_swords-randomized_morph-randomized_ganon_combo_68299872.sfc
Seed: 68299872

Description of problem:
 this seed, has the bow in Crateria in a location that either requires plasma + ice beam or a short-charge trip, but the ice beam can't be obtained without the bow

EDIT: This appears to have the same root cause as the issue from Lharm9 dated  July 12 (Issue #37 )

**Comment by tewtal** [comment]
This does not require either ice or short charging. What you need to do is start as close to the possible to the Boyon's (yellow blobs) and run left and then charge a spark. After doing so just run back to the right and jump over them while being blue from the speed charge and then spark up.
