### ISSUE TITLE
Cannot progress any further in neither of the games

### ISSUE THREAD

**Issue by 03bgood** [tewtal/alttp_sm_combo_randomizer#52]
Here's the items I have in ALTTP.

**Regular items**

Bombs
Magic Powder
Bombos Medallion
Quake Medallion
Lantern
Net

**Special items**

Pegasus Boots
Lv. 1 Power Glove
Moon Pearl

**Equipment**

Lv. 2 Sword (Master Sword)
Lv. 1 Shield
Blue Mail

**Boss items**

Pendants: 0/3
Crystals: 0/7

**Misc.**

Heart Containers: 3/17
Magic Meter: Default
Rupees: 3,428

Meanwhile in Super Metroid, I have.

**Beam**

None

**Suit**

Varia Suit

**Misc.**

Morphing Ball

**Boots**

None

I can hardly get anywhere in Super Metroid without the Morph Ball bomb and I can even get stuck in some areas since I don't have the right item. What should I do? make another ROM of the randomizer and hope I don't get stuck, again or keep trying? Let me know what areas I'm missing in Super Metroid, as am not as familiar with the game as I am ALTTP. Never got stuck in the regular ALTTP randomizer.

**Comment by drb647** [comment]
Tough to say for sure without a Spoiler file this early in the game.  There are only a few pickups I'm aware of in SM with your current equips, less if you don't have missiles:
-retro Brinstar: Morph Ball spot, 1st missile, 2nd missile and high ceiling etank with a damage boost (tournament logic)
-Crateria: Bomb Torizo (tournament logic, Alcatraz req'd for exit)
-Norfair: 2 pickups in the room before HiJump boots (warp from Death Mtn, walljump req'd for 2nd item, will softlock if you check the actual HiJump room and don't get power/bombs)
-Norfair: Ice Beam (tournament logic, mockball req'd, may have a hard time getting back out)

On the other hand, there's plenty of checks to make in ALttP with your current equips:
-Link's House
-Hyrule Castle: secret passage/uncle, dungeon, sewers/sanctuary
-Floodgate chest/sunken treasure
-Lost Woods: mushroom, thieves hideout
-Kakariko: well, Blind's hut, chicken house, bottle merchant, tavern, maze race, library
-Aginah's cave
-South Shore: Moldorm cave, ice rod cave
-Saha's hut
-East Palace up to red eyegore
-King Zora
-Pegasus rocks
-Death Mtn: Old man, Spectacle Rock cave
-Dark World via Aghinim: pyramid, catfish
-Parts of Dark palace
-Lumberjack tree post-Aghinim

**Comment by sloanr333** [comment]
Most likely, you aren't stuck. The logic has been tested to heck and back. It's still possible however, but until we know for certain, this question would best be served with some more live feedback. You can head to the #training-room text channel of the [ALttP + SM Randomizer Discord](https://discord.gg/ruN7vFf) and we'll gladly help you through it :)

**Comment by HorikawaOtane** [comment]
Do you happen to know the seed number? I can take a look at the spoiler file.

**Comment by MegGriffin42** [comment]
Welp, I'm boned. I need help advancing in ALTTP. Here's my seed:456329523
I need the Magic Mirror that's in Misery Mire, but I also need the Titan's Mitt that's in the Swamp Palace.

**Comment by Gilgatex** [comment]
This is a bug report forum.  If you need help completing a seed, please go to the discord https://discord.gg/PMKcDPQ
