### ISSUE TITLE
Bad seed.  Spoiler says bow from flute spot, but there's nothing there.

### ISSUE THREAD

**Issue by disastranagant** [tewtal/alttp_sm_combo_randomizer#6]
Console or Emulator: Bizhawk 2.2.1 snes9x core
Original Filename: Zelda no Densetsu - Kamigami no Triforce (Japan).sfc
Super Metroid (Japan, USA) (En,Ja).sfc

Seed:460439316

Description of problem:
Spoiler says the D was supposed to be at the flute spot but nothing actually comes out of the hole.  The jingle plays but no item.  Continues to happen if I leave and come back.
Spoiler (if available):
{
    "Light World": {
        "Sahasrahla's Hut - Left": "Plasma Beam",
        "Sahasrahla's Hut - Middle": "Twenty Rupees",
        "Sahasrahla's Hut - Right": "Heart Container",
        "Sahasrahla": "Twenty Rupees",
        "King Zora": "Bomb Upgrade (+5)",
        "Potion Shop": "Heart Container",
        "Zora's Ledge": "Missile",
        "Waterfall Fairy - Left": "Super Missile",
        "Waterfall Fairy - Right": "Silver Arrows Upgrade",
        "Master Sword Pedestal": "Twenty Rupees",
        "King's Tomb": "Twenty Rupees",
        "Kakariko Tavern": "Pegasus Boots",
        "Chicken House": "Magic Powder",
        "Kakariko Well - Top": "Missile",
        "Kakariko Well - Left": "Bomb Upgrade (+5)",
        "Kakariko Well - Middle": "Progressive Shield",
        "Kakariko Well - Right": "Three Bombs",
        "Kakariko Well - Bottom": "Reserve Tank",
        "Blind's Hideout - Top": "Power Bomb",
        "Blind's Hideout - Left": "Arrow Upgrade (+5)",
        "Blind's Hideout - Right": "Shovel",
        "Blind's Hideout - Far Left": "Fire Rod",
        "Blind's Hideout - Far Right": "Missile",
        "Pegasus Rocks": "Super Missile",
        "Bottle Merchant": "Missile",
        "Magic Bat": "Power Bomb",
        "Sick Kid": "Missile",
        "Lost Woods Hideout": "Progressive Shield",
        "Lumberjack Tree": "Piece Of Heart",
        "Graveyard Ledge": "Fifty Rupees",
        "Mushroom": "Reserve Tank",
        "Floodgate Chest": "Magic Cape",
        "Link's House": "Hi-Jump Boots",
        "Aginah's Cave": "Energy Tank",
        "Mini Moldorm Cave - Far Left": "Arrow Upgrade (+5)",
        "Mini Moldorm Cave - Left": "Three Hundred Rupees",
        "Mini Moldorm Cave - Right": "Super Missile",
        "Mini Moldorm Cave - Far Right": "Twenty Rupees",
        "Ice Rod Cave": "Energy Tank",
        "Hobo": "Energy Tank",
        "Bombos Tablet": "Bottle (Red Potion)",
        "Cave 45": "Gravity Suit",
        "Checkerboard Cave": "Twenty Rupees",
        "Mini Moldorm Cave - NPC": "Energy Tank",
        "Library": "Super Missile",
        "Maze Race": "Bottle (Bee)",
        "Desert Ledge": "Arrow Upgrade (+5)",
        "Lake Hylia Island": "Fifty Rupees",
        "Sunken Treasure": "Twenty Rupees",
        "Flute Spot": "Bow"
    },
    "Hyrule Castle": {
        "Sanctuary": "Sewers Key",
        "Sewers - Secret Room - Left": "Sewers Map",
        "Sewers - Secret Room - Middle": "One Rupee",
        "Sewers - Secret Room - Right": "Power Bomb",
        "Sewers - Dark Cross": "Super Missile",
        "Hyrule Castle - Boomerang Chest": "Missile",
        "Hyrule Castle - Map Chest": "Morphing Ball",
        "Hyrule Castle - Zelda's Cell": "Power Bomb",
        "Link's Uncle": "Twenty Rupees",
        "Secret Passage": "Five Rupees"
    },
    "Eastern Palace": {
        "Eastern Palace - Compass Chest": "Bomb Upgrade (+5)",
        "Eastern Palace - Big Chest": "Eastern Palace Compass",
        "Eastern Palace - Cannonball Chest": "Eastern Palace Big Key",
        "Eastern Palace - Big Key Chest": "Missile",
        "Eastern Palace - Map Chest": "Eastern Palace Map",
        "Eastern Palace - Armos Knights": "Bomb Upgrade (+5)",
        "Eastern Palace - Prize": "Crystal 3"
    },
    "Desert Palace": {
        "Desert Palace - Big Chest": "Desert Palace Map",
        "Desert Palace - Map Chest": "Desert Palace Key",
        "Desert Palace - Torch": "Desert Palace Compass",
        "Desert Palace - Big Key Chest": "Missile",
        "Desert Palace - Compass Chest": "Desert Palace Big Key",
        "Desert Palace - Lanmolas'": "Missile",
        "Desert Palace - Prize": "Pendant Of Power"
    },
    "Death Mountain": {
        "Old Man": "Bomb Upgrade (+5)",
        "Spectacle Rock Cave": "Piece Of Heart",
        "Ether Tablet": "Energy Tank",
        "Spectacle Rock": "Bug Catching Net",
        "Spiral Cave": "Heart Container",
        "Mimic Cave": "Fifty Rupees",
        "Paradox Cave Lower - Far Left": "Ten Arrows",
        "Paradox Cave Lower - Left": "Heart Container",
        "Paradox Cave Lower - Right": "Ice Rod",
        "Paradox Cave Lower - Far Right": "Power Bomb",
        "Paradox Cave Lower - Middle": "Missile",
        "Paradox Cave Upper - Left": "Ten Arrows",
        "Paradox Cave Upper - Right": "Fifty Rupees",
        "Floating Island": "Missile"
    },
    "Tower Of Hera": {
        "Tower of Hera - Big Key Chest": "Spazer",
        "Tower of Hera - Basement Cage": "Tower of Hera Big Key",
        "Tower of Hera - Map Chest": "Twenty Rupees",
        "Tower of Hera - Compass Chest": "Tower of Hera Key",
        "Tower of Hera - Big Chest": "Tower of Hera Compass",
        "Tower of Hera - Moldorm": "Tower of Hera Map",
        "Tower of Hera - Prize": "Crystal 1"
    },
    "Castle Tower": {
        "Castle Tower - Room 03": "Agahnims Tower Key",
        "Castle Tower - Dark Maze": "Agahnims Tower Key"
    },
    "Dark World": {
        "Superbunny Cave - Top": "Three Hundred Rupees",
        "Superbunny Cave - Bottom": "Screw Attack",
        "Hookshot Cave - Top Right": "Missile",
        "Hookshot Cave - Top Left": "Piece Of Heart",
        "Hookshot Cave - Bottom Left": "Twenty Rupees",
        "Hookshot Cave - Bottom Right": "Wave Beam",
        "Spike Cave": "Progressive Sword",
        "Catfish": "Ten Arrows",
        "Pyramid": "Missile",
        "Pyramid Fairy - Left": "Super Missile",
        "Pyramid Fairy - Right": "Missile",
        "Brewery": "Heart Container",
        "C-Shaped House": "Twenty Rupees",
        "Chest Game": "Missile",
        "Hammer Pegs": "Progressive Armor",
        "Bumper Cave": "Super Missile",
        "Blacksmith": "Magic Mirror",
        "Purple Chest": "Super Missile",
        "Hype Cave - Top": "Progressive Sword",
        "Hype Cave - Middle Right": "Energy Tank",
        "Hype Cave - Middle Left": "Progressive Shield",
        "Hype Cave - Bottom": "X-Ray Scope",
        "Stumpy": "Bombs",
        "Hype Cave - NPC": "Three Bombs",
        "Digging Game": "Piece Of Heart",
        "Mire Shed - Left": "Progressive Sword",
        "Mire Shed - Right": "Arrow Upgrade (+5)"
    },
    "Dark Palace": {
        "Palace of Darkness - Shooter Room": "Palace of Darkness Key",
        "Palace of Darkness - Big Key Chest": "Palace of Darkness Key",
        "Palace of Darkness - The Arena - Ledge": "Palace of Darkness Key",
        "Palace of Darkness - The Arena - Bridge": "Palace of Darkness Key",
        "Palace of Darkness - Stalfos Basement": "Palace of Darkness Key",
        "Palace of Darkness - Map Chest": "Book Of Mudora",
        "Palace of Darkness - Big Chest": "Missile",
        "Palace of Darkness - Compass Chest": "Palace of Darkness Big Key",
        "Palace of Darkness - Harmless Hellway": "Palace of Darkness Key",
        "Palace of Darkness - Dark Basement - Left": "Missile",
        "Palace of Darkness - Dark Basement - Right": "Palace of Darkness Compass",
        "Palace of Darkness - Dark Maze - Top": "Palace of Darkness Map",
        "Palace of Darkness - Dark Maze - Bottom": "Hammer",
        "Palace of Darkness - Helmasaur King": "Twenty Rupees",
        "Palace of Darkness - Prize": "Crystal 2"
    },
    "Swamp Palace": {
        "Swamp Palace - Entrance": "Swamp Palace Key",
        "Swamp Palace - Big Chest": "Swamp Palace Map",
        "Swamp Palace - Big Key Chest": "Energy Tank",
        "Swamp Palace - Map Chest": "Piece Of Heart",
        "Swamp Palace - West Chest": "Super Missile",
        "Swamp Palace - Compass Chest": "Swamp Palace Compass",
        "Swamp Palace - Flooded Room - Left": "Missile",
        "Swamp Palace - Flooded Room - Right": "Swamp Palace Big Key",
        "Swamp Palace - Waterfall Room": "Twenty Rupees",
        "Swamp Palace - Arrghus": "Ether",
        "Swamp Palace - Prize": "Crystal 5"
    },
    "Skull Woods": {
        "Skull Woods - Big Chest": "Progressive Glove",
        "Skull Woods - Big Key Chest": "Arrow Upgrade (+5)",
        "Skull Woods - Compass Chest": "Skull Woods Map",
        "Skull Woods - Map Chest": "Skull Woods Key",
        "Skull Woods - Bridge Room": "Skull Woods Key",
        "Skull Woods - Pot Prison": "Skull Woods Compass",
        "Skull Woods - Pinball Room": "Skull Woods Key",
        "Skull Woods - Mothula": "Skull Woods Big Key",
        "Skull Woods - Prize": "Crystal 4"
    },
    "Thieves Town": {
        "Thieves' Town - Attic": "Thieves Town Compass",
        "Thieves' Town - Big Key Chest": "Piece Of Heart",
        "Thieves' Town - Map Chest": "Thieves Town Big Key",
        "Thieves' Town - Compass Chest": "One Hundred Rupees",
        "Thieves' Town - Ambush Chest": "Thieves Town Map",
        "Thieves' Town - Big Chest": "Thieves Town Key",
        "Thieves' Town - Blind's Cell": "Missile",
        "Thieves' Town - Blind": "Heart Container",
        "Thieves' Town - Prize": "Pendant Of Wisdom"
    },
    "Ice Palace": {
        "Ice Palace - Big Key Chest": "Ice Palace Key",
        "Ice Palace - Compass Chest": "Missile",
        "Ice Palace - Map Chest": "Energy Tank",
        "Ice Palace - Spike Room": "Ice Palace Map",
        "Ice Palace - Freezor Chest": "Ice Palace Key",
        "Ice Palace - Iced T Room": "Ice Palace Big Key",
        "Ice Palace - Big Chest": "Ice Palace Compass",
        "Ice Palace - Kholdstare": "Ten Bombs",
        "Ice Palace - Prize": "Crystal 7"
    },
    "Misery Mire": {
        "Misery Mire - Big Chest": "Misery Mire Key",
        "Misery Mire - Main Lobby": "Misery Mire Big Key",
        "Misery Mire - Big Key Chest": "Missile",
        "Misery Mire - Compass Chest": "Three Hundred Rupees",
        "Misery Mire - Bridge Chest": "Misery Mire Key",
        "Misery Mire - Map Chest": "Misery Mire Key",
        "Misery Mire - Spike Chest": "Misery Mire Compass",
        "Misery Mire - Vitreous": "Misery Mire Map",
        "Misery Mire - Prize": "Pendant Of Courage"
    },
    "Turtle Rock": {
        "Turtle Rock - Chain Chomps": "Turtle Rock Key",
        "Turtle Rock - Compass Chest": "Turtle Rock Compass",
        "Turtle Rock - Roller Room - Left": "Progressive Sword",
        "Turtle Rock - Roller Room - Right": "Turtle Rock Key",
        "Turtle Rock - Big Chest": "Turtle Rock Key",
        "Turtle Rock - Big Key Chest": "Turtle Rock Big Key",
        "Turtle Rock - Crystaroller Room": "Power Bomb",
        "Turtle Rock - Eye Bridge - Bottom Left": "Energy Tank",
        "Turtle Rock - Eye Bridge - Bottom Right": "Turtle Rock Map",
        "Turtle Rock - Eye Bridge - Top Left": "Turtle Rock Key",
        "Turtle Rock - Eye Bridge - Top Right": "Varia Suit",
        "Turtle Rock - Trinexx": "Missile",
        "Turtle Rock - Prize": "Crystal 6"
    },
    "Ganons Tower": {
        "Ganon's Tower - Bob's Torch": "Ganons Tower Key",
        "Ganon's Tower - DMs Room - Top Left": "Ganons Tower Big Key",
        "Ganon's Tower - DMs Room - Top Right": "Energy Tank",
        "Ganon's Tower - DMs Room - Bottom Left": "Ganons Tower Key",
        "Ganon's Tower - DMs Room - Bottom Right": "Power Bomb",
        "Ganon's Tower - Randomizer Room - Top Left": "Energy Tank",
        "Ganon's Tower - Randomizer Room - Top Right": "Ganons Tower Compass",
        "Ganon's Tower - Randomizer Room - Bottom Left": "Piece Of Heart",
        "Ganon's Tower - Randomizer Room - Bottom Right": "Reserve Tank",
        "Ganon's Tower - Firesnake Room": "Mushroom",
        "Ganon's Tower - Map Chest": "Energy Tank",
        "Ganon's Tower - Big Chest": "Three Bombs",
        "Ganon's Tower - Hope Room - Left": "Ganons Tower Key",
        "Ganon's Tower - Hope Room - Right": "Piece Of Heart",
        "Ganon's Tower - Bob's Chest": "Missile",
        "Ganon's Tower - Tile Room": "Cane Of Byrna",
        "Ganon's Tower - Compass Room - Top Left": "Three Bombs",
        "Ganon's Tower - Compass Room - Top Right": "Three Hundred Rupees",
        "Ganon's Tower - Compass Room - Bottom Left": "Piece Of Heart",
        "Ganon's Tower - Compass Room - Bottom Right": "Three Bombs",
        "Ganon's Tower - Big Key Chest": "Twenty Rupees",
        "Ganon's Tower - Big Key Room - Left": "Twenty Rupees",
        "Ganon's Tower - Big Key Room - Right": "Ganons Tower Key",
        "Ganon's Tower - Mini Helmasaur Room - Left": "Half Magic",
        "Ganon's Tower - Mini Helmasaur Room - Right": "Twenty Rupees",
        "Ganon's Tower - Pre-Moldorm Chest": "Twenty Rupees",
        "Ganon's Tower - Moldorm Chest": "Ganons Tower Map"
    },
    "Special": {
        "Turtle Rock Medallion": "Bombos",
        "Misery Mire Medallion": "Bombos",
        "Waterfall Bottle": "Bottle (Green Potion)",
        "Pyramid Bottle": "Bottle (Golden Bee)"
    },
    "Crateria": {
        "Power Bomb (Crateria surface)": "Piece Of Heart",
        "Missile (Crateria middle)": "Missile",
        "Missile (Crateria bottom)": "Piece Of Heart",
        "Super Missile (Crateria)": "Piece Of Heart",
        "Bombs": "Twenty Rupees",
        "Energy Tank, Terminator": "Missile",
        "Energy Tank, Gauntlet": "Heart Container",
        "Missile (Crateria gauntlet right)": "Piece Of Heart",
        "Missile (Crateria gauntlet left)": "Three Bombs",
        "Missile (outside Wrecked Ship bottom)": "Piece Of Heart",
        "Missile (outside Wrecked Ship top)": "Missile",
        "Missile (outside Wrecked Ship middle)": "Single Arrow",
        "Missile (Crateria moat)": "Bomb Upgrade (+5)"
    },
    "Brinstar": {
        "Power Bomb (green Brinstar bottom)": "Missile",
        "Missile (green Brinstar below super missile)": "Progressive Glove",
        "Super Missile (green Brinstar top)": "Missile",
        "Reserve Tank, Brinstar": "Three Bombs",
        "Missile (green Brinstar behind missile)": "Piece Of Heart",
        "Missile (green Brinstar behind reserve tank)": "Reserve Tank",
        "Energy Tank, Etecoons": "Lamp",
        "Super Missile (green Brinstar bottom)": "Charge Beam",
        "Super Missile (pink Brinstar)": "Piece Of Heart",
        "Missile (pink Brinstar top)": "Missile",
        "Missile (pink Brinstar bottom)": "Missile",
        "Charge Beam": "Missile",
        "Power Bomb (pink Brinstar)": "Heart Container",
        "Missile (green Brinstar pipe)": "Piece Of Heart",
        "Energy Tank, Waterway": "Quake",
        "Energy Tank, Brinstar Gate": "Five Rupees",
        "Morphing Ball": "Heart Container",
        "Power Bomb (blue Brinstar)": "Power Bomb",
        "Missile (blue Brinstar middle)": "Three Bombs",
        "Energy Tank, Brinstar Ceiling": "Ice Beam",
        "Missile (blue Brinstar bottom)": "Twenty Rupees",
        "Missile (blue Brinstar top)": "Super Missile",
        "Missile (blue Brinstar behind missile)": "Spring Ball",
        "X-Ray Scope": "Flute",
        "Power Bomb (red Brinstar sidehopper room)": "Super Missile",
        "Power Bomb (red Brinstar spike room)": "Twenty Rupees",
        "Missile (red Brinstar spike room)": "Five Rupees",
        "Spazer": "Grappling Beam",
        "Energy Tank, Kraid": "Blue Boomerang",
        "Varia Suit": "Missile",
        "Missile (Kraid)": "Super Missile"
    },
    "Norfair": {
        "Ice Beam": "Progressive Armor",
        "Missile (below Ice Beam)": "Sancturary Heart Container",
        "Hi-Jump Boots": "Hookshot",
        "Missile (Hi-Jump Boots)": "Flippers",
        "Energy Tank (Hi-Jump Boots)": "Three Bombs",
        "Missile (lava room)": "Arrow Upgrade (+10)",
        "Reserve Tank, Norfair": "Piece Of Heart",
        "Missile (Norfair Reserve Tank)": "Missile",
        "Missile (bubble Norfair green door)": "Magical Boomerang",
        "Missile (bubble Norfair)": "Ten Arrows",
        "Missile (Speed Booster)": "Piece Of Heart",
        "Speed Booster": "Three Hundred Rupees",
        "Missile (Wave Beam)": "Missile",
        "Wave Beam": "Fifty Rupees",
        "Energy Tank, Crocomire": "Speed Booster",
        "Missile (above Crocomire)": "Missile",
        "Power Bomb (Crocomire)": "Piece Of Heart",
        "Missile (below Crocomire)": "Twenty Rupees",
        "Missile (Grapple Beam)": "Twenty Rupees",
        "Grapple Beam": "Cane Of Somaria"
    },
    "Lower Norfair": {
        "Missile (Gold Torizo)": "Super Missile",
        "Super Missile (Gold Torizo)": "Fifty Rupees",
        "Screw Attack": "Super Missile",
        "Missile (Mickey Mouse room)": "Fifty Rupees",
        "Missile (lower Norfair above fire flea room)": "Arrow Upgrade (+5)",
        "Power Bomb (lower Norfair above fire flea room)": "Space Jump",
        "Power Bomb (Power Bombs of shame)": "Twenty Rupees",
        "Missile (lower Norfair near Wave Beam)": "Twenty Rupees",
        "Energy Tank, Ridley": "Super Missile",
        "Energy Tank, Firefleas": "Twenty Rupees"
    },
    "Wrecked Ship": {
        "Missile (Wrecked Ship middle)": "Missile",
        "Reserve Tank, Wrecked Ship": "Piece Of Heart",
        "Missile (Gravity Suit)": "Power Bomb",
        "Missile (Wrecked Ship top)": "Twenty Rupees",
        "Energy Tank, Wrecked Ship": "Bottle (Fairy)",
        "Super Missile (Wrecked Ship left)": "Twenty Rupees",
        "Right Super, Wrecked Ship": "Super Missile",
        "Gravity Suit": "Bombos"
    },
    "Maridia": {
        "Missile (green Maridia shinespark)": "Energy Tank",
        "Super Missile (green Maridia)": "Piece Of Heart",
        "Energy Tank, Mama turtle": "Power Bomb",
        "Missile (green Maridia tatori)": "Missile",
        "Super Missile (yellow Maridia)": "Bottle (Red Potion)",
        "Missile (yellow Maridia super missile)": "Super Missile",
        "Missile (yellow Maridia false wall)": "One Rupee",
        "Plasma Beam": "Five Rupees",
        "Missile (left Maridia sand pit room)": "Piece Of Heart",
        "Reserve Tank, Maridia": "Heart Container",
        "Missile (right Maridia sand pit room)": "Moon Pearl",
        "Power Bomb (right Maridia sand pit room)": "Missile",
        "Missile (pink Maridia)": "Ten Arrows",
        "Super Missile (pink Maridia)": "Energy Tank",
        "Spring Ball": "Twenty Rupees",
        "Missile (Draygon)": "Missile",
        "Energy Tank, Botwoon": "Piece Of Heart",
        "Space Jump": "Bomb Upgrade (+10)"
    },
    "Tourian": [],
    "playthrough": {
        "1": {
            "Light World": {
                "Kakariko Tavern": "Pegasus Boots",
                "Blind's Hideout - Top": "Power Bomb",
                "Blind's Hideout - Right": "Shovel",
                "Blind's Hideout - Far Left": "Fire Rod",
                "Floodgate Chest": "Magic Cape",
                "Link's House": "Hi-Jump Boots",
                "Aginah's Cave": "Energy Tank",
                "Mini Moldorm Cave - Right": "Super Missile",
                "Ice Rod Cave": "Energy Tank",
                "Mini Moldorm Cave - NPC": "Energy Tank"
            },
            "Hyrule Castle": {
                "Hyrule Castle - Map Chest": "Morphing Ball"
            },
            "Eastern Palace": {
                "Eastern Palace - Cannonball Chest": "Eastern Palace Big Key"
            },
            "Brinstar": {
                "Energy Tank, Brinstar Ceiling": "Ice Beam"
            }
        },
        "2": {
            "Light World": {
                "Flute Spot": "Bow"
            },
            "Brinstar": {
                "Missile (green Brinstar below super missile)": "Progressive Glove",
                "Energy Tank, Etecoons": "Lamp",
                "Super Missile (green Brinstar bottom)": "Charge Beam",
                "Spazer": "Grappling Beam",
                "Kraid": "Defeat Kraid"
            },
            "Norfair": {
                "Hi-Jump Boots": "Hookshot",
                "Missile (Hi-Jump Boots)": "Flippers",
                "Grapple Beam": "Cane Of Somaria"
            },
            "Wrecked Ship": {
                "Gravity Suit": "Bombos",
                "Phantoon": "Defeat Phantoon"
            }
        },
        "3": {
            "Eastern Palace": {
                "Eastern Palace - Prize": "Crystal 3"
            },
            "Death Mountain": {
                "Paradox Cave Lower - Right": "Ice Rod"
            },
            "Maridia": {
                "Missile (right Maridia sand pit room)": "Moon Pearl"
            }
        },
        "4": {
            "Dark World": {
                "Hype Cave - Top": "Progressive Sword"
            }
        },
        "5": {
            "Skull Woods": {
                "Skull Woods - Mothula": "Skull Woods Big Key",
                "Skull Woods - Prize": "Crystal 4"
            }
        },
        "6": {
            "Dark Palace": {
                "Palace of Darkness - Compass Chest": "Palace of Darkness Big Key",
                "Palace of Darkness - Dark Maze - Bottom": "Hammer"
            },
            "Skull Woods": {
                "Skull Woods - Big Chest": "Progressive Glove"
            }
        },
        "7": {
            "Tower Of Hera": {
                "Tower of Hera - Basement Cage": "Tower of Hera Big Key"
            },
            "Dark World": {
                "Blacksmith": "Magic Mirror"
            },
            "Dark Palace": {
                "Palace of Darkness - Prize": "Crystal 2"
            },
            "Ice Palace": {
                "Ice Palace - Iced T Room": "Ice Palace Big Key"
            },
            "Turtle Rock": {
                "Turtle Rock - Roller Room - Left": "Progressive Sword"
            }
        },
        "8": {
            "Light World": {
                "Cave 45": "Gravity Suit"
            },
            "Tower Of Hera": {
                "Tower of Hera - Prize": "Crystal 1"
            },
            "Ice Palace": {
                "Ice Palace - Prize": "Crystal 7"
            }
        },
        "9": {
            "Swamp Palace": {
                "Swamp Palace - Prize": "Crystal 5"
            },
            "Turtle Rock": {
                "Turtle Rock - Big Key Chest": "Turtle Rock Big Key"
            },
            "Maridia": {
                "Draygon": "Defeat Draygon"
            }
        },
        "10": {
            "Turtle Rock": {
                "Turtle Rock - Eye Bridge - Top Right": "Varia Suit"
            }
        },
        "11": {
            "Turtle Rock": {
                "Turtle Rock - Prize": "Crystal 6"
            },
            "Lower Norfair": {
                "Ridley": "Defeat Ridley"
            }
        },
        "12": {
            "Tourian": {
                "Mother Brain": "Defeat Mother Brain"
            }
        },
        "13": {
            "Ganons Tower": {
                "Ganon's Tower - DMs Room - Top Left": "Ganons Tower Big Key"
            }
        },
        "14": {
            "Ganons Tower": {
                "Agahnim 2": "Defeat Agahnim 2"
            }
        },
        "15": {
            "Dark World": {
                "Ganon": "Triforce"
            }
        },
        "longest_item_chain": 15,
        "regions_visited": 33
    },
    "meta": {
        "difficulty": "normal",
        "variation": "combo",
        "logic": "no-glitches-v8.1",
        "rom_mode": "NoMajorGlitches",
        "seed": 460439316,
        "goal": "ganon",
        "build": "2018-05-14",
        "mode": "open",
        "weapons": "randomized"
    }
}

**Comment by tewtal** [comment]
This is a known issue where the item somehow teleports all the way to the right side of the grove when you dig the item up. It'll be fixed as soon as possible but in the meantime the workaround is to just go right after digging and hopefully find the item there.

**Comment by tewtal** [comment]
This has now been fixed as of V9.
