### ISSUE TITLE
ROM DOESNT WORK ON SNES CLASSIC

### ISSUE THREAD

**Issue by earthbound81** [tewtal/alttp_sm_combo_randomizer#61]
Console or Emulator:

 If emulator state which emulator and version.

Original Filename:

Seed:

Item, Entrance or Custom: 

Mode: 
Logic: 
Goal: 
Difficulty: 
Variation: 

Description of problem:

Spoiler (if available):

**Comment by earthbound81** [comment]
The randomizer rom doesnt load on snes classic. anyone know why? or know a fix for this?

**Comment by SmolBig** [comment]
Please do not ask for tech support here. You can get help in the Discord.

**Comment by tewtal** [comment]
Unfortunately the standard emulator (Canoe) on the SNES Classic does not support ExHiROM-games like this hack. You will have to install an external emulator, for example Retroarch.
