### ISSUE TITLE
Stuck in the escape sequence after beating mother brain

### ISSUE THREAD

**Issue by elreymu** [tewtal/alttp_sm_combo_randomizer#62]
Console or Emulator:
Emulator
 If emulator state which emulator and version.
Snes9x 1.55
Original Filename:
SMALttP - sm-normal_alttp-no-glitches-v10_normal-open_swords-randomized_morph-vanilla_ganon_combo_249741066
Seed:
249741066

I beat mother brain before ganon and got stuck in the room between tourian and crateria, can't break the wall in front, i don't have speedbooster though, is it required for this part?
Screenshot
https://imgur.com/a/ZikTr95

**Comment by drb647** [comment]
Speed, bombs or screw attack will break the wall.  Otherwise, you're softlocked.

**Comment by CapnCrinklepants** [comment]
If you've beaten SM first, the flag that registers you've beaten MB gets
set immediately so you can safely reset and continue in LttP and it should
complete as normal.

I submitted a PR just yesterday to the rom that will simply remove those
blocks when entering that room from Tourian, so it shouldn't be an issue in
the future.

-Sloan Reynolds
sloan@lanimals.com
530-962-0555

**Comment by tewtal** [comment]
A fix for this will be included in the next update.
