### ISSUE TITLE
Rom not recognized

### ISSUE THREAD

**Issue by Arenadrone** [tewtal/alttp_sm_combo_randomizer#65]
ROM not Recognized how do i fix this

**Comment by CapnCrinklepants** [comment]
The Issues board is for more issues with the code itself. If you need some general tech support please join the discord and seek answers there. https://discord.gg/ruN7vFf

Additionally, please provide more details when asking for help. We have no idea where you're seeing this error; whether it's the website, an emulator, your refrigerator, etc.
