### ISSUE TITLE
Can't enter full seed in website to access spoilers

### ISSUE THREAD

**Issue by robmenak** [tewtal/alttp_sm_combo_randomizer#68]
Seed: g5yo20JvmZ

Description of problem: I'm going to enter this seed # on the site to look at hints/spoilers but the seed field only accepts g5yo20Jvm (truncates the Z).

**Comment by Gilgatex** [comment]
That's not the right seed for what you are trying to do.  That's the permalink seed (i.e. the link you give to others to download it).  

If it's completely numeric, then it's the seed you can generate from and view spoilers on.  The numeric seed you can only see upon generation (at the bottom of the page).

Go ahead and generate a new seed, you'll see a numeric seed number at the bottom.  Click permalink and the seed changes.

This is intended behavior.

**Comment by robmenak** [comment]
Ok thanks Gilgatex

Is there any way to recover the numeric seed with this info?

Confused me because the ROM name on my first seed was completely numeric, and I was able to access spoilers. But this is my second game and the file name had the permalink seed instead of the numeric one.

**Comment by Gilgatex** [comment]
Not that I'm aware of, unfortunately

**Comment by robmenak** [comment]
Thanks. I explored a little more and got past where I was stuck, so don't need the spoliers just yet!
