### ISSUE TITLE
Continuous Walljump Required in Casual Seed

### ISSUE THREAD

**Issue by TheBlackMoogle54** [tewtal/alttp_sm_combo_randomizer#69]
Console or Emulator: snes9x

 If emulator state which emulator and version.

Original Filename: 

Seed: 18254

Item, Entrance or Custom: Morph Ball Random

Mode: 
Logic: Casual, No Glitches
Goal: 
Difficulty: 
Variation: 

Description of problem: After attempting everything in both games, I had no choice but to ultimately investigate the Spoiler Log.  In the bottom section, which is labeled as "Walkthrough", it lists "Missile (outside Wrecked Ship Bottom) - Progressive Glove" very early in the list, long before it lists the Grappling Beam or the Speed Booster, neither of which I believe that I have access to, as they require other things that I can't get yet; it lists it also before Moon Pearl, for example, with which I could access Wrecked Ship from behind.  It's possible that I'm missing something, and so I'll include the spoiler, but I'm reasonably sure that the game is telling me that I need to perform the Continuous Walljump in order to access the Wrecked Ship, and A) that is not listed as one of the required tricks in the tutorial for Casual Logic and B) I don't think it should be, since it's very hard to do.  If it IS required, please at least update the tutorial to list it as such.

Spoiler (if available):
{
    "Light World": {
        "Sahasrahla's Hut - Left": "Missile",
        "Sahasrahla's Hut - Middle": "Screw Attack",
        "Sahasrahla's Hut - Right": "Piece Of Heart",
        "Sahasrahla": "Grappling Beam",
        "King Zora": "Arrow Upgrade (+5)",
        "Potion Shop": "Heart Container",
        "Zora's Ledge": "Arrow Upgrade (+5)",
        "Waterfall Fairy - Left": "Missile",
        "Waterfall Fairy - Right": "Missile",
        "Master Sword Pedestal": "Energy Tank",
        "King's Tomb": "Fire Rod",
        "Kakariko Tavern": "Heart Container",
        "Chicken House": "Piece Of Heart",
        "Kakariko Well - Top": "Power Bomb",
        "Kakariko Well - Left": "Bomb Upgrade (+5)",
        "Kakariko Well - Middle": "Piece Of Heart",
        "Kakariko Well - Right": "Super Missile",
        "Kakariko Well - Bottom": "Piece Of Heart",
        "Blind's Hideout - Top": "Ten Arrows",
        "Blind's Hideout - Left": "Missile",
        "Blind's Hideout - Right": "Missile",
        "Blind's Hideout - Far Left": "Twenty Rupees",
        "Blind's Hideout - Far Right": "Missile",
        "Pegasus Rocks": "Bottle (Golden Bee)",
        "Bottle Merchant": "Missile",
        "Magic Bat": "Energy Tank",
        "Sick Kid": "Energy Tank",
        "Lost Woods Hideout": "Three Hundred Rupees",
        "Lumberjack Tree": "Piece Of Heart",
        "Graveyard Ledge": "Hi-Jump Boots",
        "Mushroom": "Piece Of Heart",
        "Floodgate Chest": "Bug Catching Net",
        "Link's House": "Pegasus Boots",
        "Aginah's Cave": "Bomb Upgrade (+5)",
        "Mini Moldorm Cave - Far Left": "Fifty Rupees",
        "Mini Moldorm Cave - Left": "Twenty Rupees",
        "Mini Moldorm Cave - Right": "Power Bomb",
        "Mini Moldorm Cave - Far Right": "Progressive Sword",
        "Ice Rod Cave": "Spazer",
        "Hobo": "Missile",
        "Bombos Tablet": "Quake",
        "Cave 45": "X-Ray Scope",
        "Checkerboard Cave": "Super Missile",
        "Mini Moldorm Cave - NPC": "Super Missile",
        "Library": "Reserve Tank",
        "Maze Race": "Piece Of Heart",
        "Desert Ledge": "Morphing Ball",
        "Lake Hylia Island": "Arrow Upgrade (+5)",
        "Sunken Treasure": "Bomb Upgrade (+10)",
        "Flute Spot": "Power Bomb"
    },
    "Hyrule Castle": {
        "Sanctuary": "Missile",
        "Sewers - Secret Room - Left": "Energy Tank",
        "Sewers - Secret Room - Middle": "Super Missile",
        "Sewers - Secret Room - Right": "Missile",
        "Sewers - Dark Cross": "Sewers Key",
        "Hyrule Castle - Boomerang Chest": "Missile",
        "Hyrule Castle - Map Chest": "Twenty Rupees",
        "Hyrule Castle - Zelda's Cell": "Sewers Map",
        "Link's Uncle": "Five Rupees",
        "Secret Passage": "Missile"
    },
    "Eastern Palace": {
        "Eastern Palace - Compass Chest": "Eastern Palace Big Key",
        "Eastern Palace - Big Chest": "Piece Of Heart",
        "Eastern Palace - Cannonball Chest": "Eastern Palace Map",
        "Eastern Palace - Big Key Chest": "Progressive Shield",
        "Eastern Palace - Map Chest": "Eastern Palace Compass",
        "Eastern Palace - Armos Knights": "Missile",
        "Eastern Palace - Prize": "Crystal 1"
    },
    "Desert Palace": {
        "Desert Palace - Big Chest": "Three Bombs",
        "Desert Palace - Map Chest": "Desert Palace Key",
        "Desert Palace - Torch": "Desert Palace Compass",
        "Desert Palace - Big Key Chest": "Desert Palace Big Key",
        "Desert Palace - Compass Chest": "Desert Palace Map",
        "Desert Palace - Lanmolas'": "Space Jump",
        "Desert Palace - Prize": "Crystal 3"
    },
    "Death Mountain": {
        "Old Man": "Super Missile",
        "Spectacle Rock Cave": "Energy Tank",
        "Ether Tablet": "Fifty Rupees",
        "Spectacle Rock": "Piece Of Heart",
        "Spiral Cave": "Cane Of Byrna",
        "Mimic Cave": "Bottle (Green Potion)",
        "Paradox Cave Lower - Far Left": "Three Hundred Rupees",
        "Paradox Cave Lower - Left": "Missile",
        "Paradox Cave Lower - Right": "One Rupee",
        "Paradox Cave Lower - Far Right": "Piece Of Heart",
        "Paradox Cave Lower - Middle": "Hammer",
        "Paradox Cave Upper - Left": "Fifty Rupees",
        "Paradox Cave Upper - Right": "Missile",
        "Floating Island": "Five Rupees"
    },
    "Tower Of Hera": {
        "Tower of Hera - Big Key Chest": "Tower of Hera Big Key",
        "Tower of Hera - Basement Cage": "Tower of Hera Compass",
        "Tower of Hera - Map Chest": "Tower of Hera Key",
        "Tower of Hera - Compass Chest": "Tower of Hera Map",
        "Tower of Hera - Big Chest": "Bomb Upgrade (+5)",
        "Tower of Hera - Moldorm": "Ten Arrows",
        "Tower of Hera - Prize": "Crystal 6"
    },
    "Castle Tower": {
        "Castle Tower - Room 03": "Agahnims Tower Key",
        "Castle Tower - Dark Maze": "Agahnims Tower Key"
    },
    "Dark World": {
        "Superbunny Cave - Top": "Piece Of Heart",
        "Superbunny Cave - Bottom": "Three Hundred Rupees",
        "Hookshot Cave - Top Right": "Piece Of Heart",
        "Hookshot Cave - Top Left": "Blue Boomerang",
        "Hookshot Cave - Bottom Left": "Energy Tank",
        "Hookshot Cave - Bottom Right": "Missile",
        "Spike Cave": "Progressive Armor",
        "Catfish": "Missile",
        "Pyramid": "Missile",
        "Pyramid Fairy - Left": "Twenty Rupees",
        "Pyramid Fairy - Right": "Missile",
        "Brewery": "Bombs",
        "C-Shaped House": "Ice Rod",
        "Chest Game": "Super Missile",
        "Hammer Pegs": "Reserve Tank",
        "Bumper Cave": "Three Bombs",
        "Blacksmith": "Missile",
        "Purple Chest": "Three Bombs",
        "Hype Cave - Top": "Power Bomb",
        "Hype Cave - Middle Right": "Heart Container",
        "Hype Cave - Middle Left": "Silver Arrows Upgrade",
        "Hype Cave - Bottom": "Fifty Rupees",
        "Stumpy": "Twenty Rupees",
        "Hype Cave - NPC": "Three Bombs",
        "Digging Game": "Bow",
        "Mire Shed - Left": "Arrow Upgrade (+10)",
        "Mire Shed - Right": "Twenty Rupees"
    },
    "Dark Palace": {
        "Palace of Darkness - Shooter Room": "Flippers",
        "Palace of Darkness - Big Key Chest": "Palace of Darkness Big Key",
        "Palace of Darkness - The Arena - Ledge": "Palace of Darkness Key",
        "Palace of Darkness - The Arena - Bridge": "Palace of Darkness Key",
        "Palace of Darkness - Stalfos Basement": "Palace of Darkness Key",
        "Palace of Darkness - Map Chest": "Palace of Darkness Key",
        "Palace of Darkness - Big Chest": "Plasma Beam",
        "Palace of Darkness - Compass Chest": "Palace of Darkness Key",
        "Palace of Darkness - Harmless Hellway": "Palace of Darkness Key",
        "Palace of Darkness - Dark Basement - Left": "Palace of Darkness Compass",
        "Palace of Darkness - Dark Basement - Right": "Energy Tank",
        "Palace of Darkness - Dark Maze - Top": "Charge Beam",
        "Palace of Darkness - Dark Maze - Bottom": "Heart Container",
        "Palace of Darkness - Helmasaur King": "Palace of Darkness Map",
        "Palace of Darkness - Prize": "Crystal 5"
    },
    "Swamp Palace": {
        "Swamp Palace - Entrance": "Swamp Palace Key",
        "Swamp Palace - Big Chest": "Missile",
        "Swamp Palace - Big Key Chest": "Power Bomb",
        "Swamp Palace - Map Chest": "Missile",
        "Swamp Palace - West Chest": "Progressive Armor",
        "Swamp Palace - Compass Chest": "Gravity Suit",
        "Swamp Palace - Flooded Room - Left": "Piece Of Heart",
        "Swamp Palace - Flooded Room - Right": "Swamp Palace Compass",
        "Swamp Palace - Waterfall Room": "Swamp Palace Map",
        "Swamp Palace - Arrghus": "Swamp Palace Big Key",
        "Swamp Palace - Prize": "Crystal 7"
    },
    "Skull Woods": {
        "Skull Woods - Big Chest": "Skull Woods Key",
        "Skull Woods - Big Key Chest": "Skull Woods Key",
        "Skull Woods - Compass Chest": "Skull Woods Compass",
        "Skull Woods - Map Chest": "Magic Powder",
        "Skull Woods - Bridge Room": "Skull Woods Big Key",
        "Skull Woods - Pot Prison": "Skull Woods Map",
        "Skull Woods - Pinball Room": "Skull Woods Key",
        "Skull Woods - Mothula": "Twenty Rupees",
        "Skull Woods - Prize": "Pendant Of Courage"
    },
    "Thieves Town": {
        "Thieves' Town - Attic": "Super Missile",
        "Thieves' Town - Big Key Chest": "Power Bomb",
        "Thieves' Town - Map Chest": "Thieves Town Big Key",
        "Thieves' Town - Compass Chest": "Magical Boomerang",
        "Thieves' Town - Ambush Chest": "Thieves Town Compass",
        "Thieves' Town - Big Chest": "Thieves Town Key",
        "Thieves' Town - Blind's Cell": "Thieves Town Map",
        "Thieves' Town - Blind": "Energy Tank",
        "Thieves' Town - Prize": "Pendant Of Wisdom"
    },
    "Ice Palace": {
        "Ice Palace - Big Key Chest": "Ice Palace Key",
        "Ice Palace - Compass Chest": "Twenty Rupees",
        "Ice Palace - Map Chest": "Power Bomb",
        "Ice Palace - Spike Room": "Ice Palace Big Key",
        "Ice Palace - Freezor Chest": "Ice Palace Key",
        "Ice Palace - Iced T Room": "Ice Palace Compass",
        "Ice Palace - Big Chest": "Energy Tank",
        "Ice Palace - Kholdstare": "Ice Palace Map",
        "Ice Palace - Prize": "Pendant Of Power"
    },
    "Misery Mire": {
        "Misery Mire - Big Chest": "Bomb Upgrade (+5)",
        "Misery Mire - Main Lobby": "Misery Mire Map",
        "Misery Mire - Big Key Chest": "Misery Mire Key",
        "Misery Mire - Compass Chest": "Misery Mire Big Key",
        "Misery Mire - Bridge Chest": "Misery Mire Key",
        "Misery Mire - Map Chest": "Misery Mire Key",
        "Misery Mire - Spike Chest": "Twenty Rupees",
        "Misery Mire - Vitreous": "Misery Mire Compass",
        "Misery Mire - Prize": "Crystal 2"
    },
    "Turtle Rock": {
        "Turtle Rock - Chain Chomps": "Energy Tank",
        "Turtle Rock - Compass Chest": "Turtle Rock Key",
        "Turtle Rock - Roller Room - Left": "Three Bombs",
        "Turtle Rock - Roller Room - Right": "Turtle Rock Key",
        "Turtle Rock - Big Chest": "Turtle Rock Key",
        "Turtle Rock - Big Key Chest": "Turtle Rock Big Key",
        "Turtle Rock - Crystaroller Room": "Bomb Upgrade (+5)",
        "Turtle Rock - Eye Bridge - Bottom Left": "Progressive Shield",
        "Turtle Rock - Eye Bridge - Bottom Right": "Turtle Rock Map",
        "Turtle Rock - Eye Bridge - Top Left": "Turtle Rock Key",
        "Turtle Rock - Eye Bridge - Top Right": "Turtle Rock Compass",
        "Turtle Rock - Trinexx": "Heart Container",
        "Turtle Rock - Prize": "Crystal 4"
    },
    "Ganons Tower": {
        "Ganon's Tower - Bob's Torch": "Ganons Tower Key",
        "Ganon's Tower - DMs Room - Top Left": "Ganons Tower Key",
        "Ganon's Tower - DMs Room - Top Right": "Arrow Upgrade (+5)",
        "Ganon's Tower - DMs Room - Bottom Left": "Ten Arrows",
        "Ganon's Tower - DMs Room - Bottom Right": "Ganons Tower Key",
        "Ganon's Tower - Randomizer Room - Top Left": "Super Missile",
        "Ganon's Tower - Randomizer Room - Top Right": "One Rupee",
        "Ganon's Tower - Randomizer Room - Bottom Left": "Ganons Tower Compass",
        "Ganon's Tower - Randomizer Room - Bottom Right": "Missile",
        "Ganon's Tower - Firesnake Room": "Twenty Rupees",
        "Ganon's Tower - Map Chest": "Arrow Upgrade (+5)",
        "Ganon's Tower - Big Chest": "Ganons Tower Key",
        "Ganon's Tower - Hope Room - Left": "Ganons Tower Map",
        "Ganon's Tower - Hope Room - Right": "Ganons Tower Big Key",
        "Ganon's Tower - Bob's Chest": "Energy Tank",
        "Ganon's Tower - Tile Room": "Twenty Rupees",
        "Ganon's Tower - Compass Room - Top Left": "Three Hundred Rupees",
        "Ganon's Tower - Compass Room - Top Right": "Missile",
        "Ganon's Tower - Compass Room - Bottom Left": "Ten Arrows",
        "Ganon's Tower - Compass Room - Bottom Right": "Twenty Rupees",
        "Ganon's Tower - Big Key Chest": "Twenty Rupees",
        "Ganon's Tower - Big Key Room - Left": "Super Missile",
        "Ganon's Tower - Big Key Room - Right": "Three Bombs",
        "Ganon's Tower - Mini Helmasaur Room - Left": "Twenty Rupees",
        "Ganon's Tower - Mini Helmasaur Room - Right": "Piece Of Heart",
        "Ganon's Tower - Pre-Moldorm Chest": "Missile",
        "Ganon's Tower - Moldorm Chest": "Twenty Rupees"
    },
    "Special": {
        "Turtle Rock Medallion": "Ether",
        "Misery Mire Medallion": "Ether",
        "Waterfall Bottle": "Bottle (Golden Bee)",
        "Pyramid Bottle": "Bottle (Bee)"
    },
    "Crateria": {
        "Power Bomb (Crateria surface)": "Half Magic",
        "Missile (Crateria middle)": "Missile",
        "Missile (Crateria bottom)": "Book Of Mudora",
        "Super Missile (Crateria)": "Moon Pearl",
        "Bombs": "Reserve Tank",
        "Energy Tank, Terminator": "Piece Of Heart",
        "Energy Tank, Gauntlet": "Bomb Upgrade (+5)",
        "Missile (Crateria gauntlet right)": "Missile",
        "Missile (Crateria gauntlet left)": "Twenty Rupees",
        "Missile (outside Wrecked Ship bottom)": "Progressive Glove",
        "Missile (outside Wrecked Ship top)": "Power Bomb",
        "Missile (outside Wrecked Ship middle)": "Super Missile",
        "Missile (Crateria moat)": "Five Rupees"
    },
    "Brinstar": {
        "Power Bomb (green Brinstar bottom)": "Twenty Rupees",
        "Missile (green Brinstar below super missile)": "Power Bomb",
        "Super Missile (green Brinstar top)": "Mushroom",
        "Reserve Tank, Brinstar": "Heart Container",
        "Missile (green Brinstar behind missile)": "Missile",
        "Missile (green Brinstar behind reserve tank)": "Piece Of Heart",
        "Energy Tank, Etecoons": "Twenty Rupees",
        "Super Missile (green Brinstar bottom)": "Bottle (Fairy)",
        "Super Missile (pink Brinstar)": "Energy Tank",
        "Missile (pink Brinstar top)": "Spring Ball",
        "Missile (pink Brinstar bottom)": "Wave Beam",
        "Charge Beam": "Missile",
        "Power Bomb (pink Brinstar)": "Ten Bombs",
        "Missile (green Brinstar pipe)": "Sancturary Heart Container",
        "Energy Tank, Waterway": "Super Missile",
        "Energy Tank, Brinstar Gate": "Super Missile",
        "Morphing Ball": "Missile",
        "Power Bomb (blue Brinstar)": "Lamp",
        "Missile (blue Brinstar middle)": "Piece Of Heart",
        "Energy Tank, Brinstar Ceiling": "Heart Container",
        "Missile (blue Brinstar bottom)": "Missile",
        "Missile (blue Brinstar top)": "Missile",
        "Missile (blue Brinstar behind missile)": "Piece Of Heart",
        "X-Ray Scope": "Fifty Rupees",
        "Power Bomb (red Brinstar sidehopper room)": "Super Missile",
        "Power Bomb (red Brinstar spike room)": "Twenty Rupees",
        "Missile (red Brinstar spike room)": "Varia Suit",
        "Spazer": "Bombos",
        "Energy Tank, Kraid": "Cane Of Somaria",
        "Varia Suit": "Progressive Sword",
        "Missile (Kraid)": "Progressive Sword"
    },
    "Norfair": {
        "Ice Beam": "Heart Container",
        "Missile (below Ice Beam)": "Shovel",
        "Hi-Jump Boots": "Hookshot",
        "Missile (Hi-Jump Boots)": "Missile",
        "Energy Tank (Hi-Jump Boots)": "Missile",
        "Missile (lava room)": "Heart Container",
        "Reserve Tank, Norfair": "Fifty Rupees",
        "Missile (Norfair Reserve Tank)": "Three Bombs",
        "Missile (bubble Norfair green door)": "Twenty Rupees",
        "Missile (bubble Norfair)": "Single Arrow",
        "Missile (Speed Booster)": "Speed Booster",
        "Speed Booster": "Arrow Upgrade (+5)",
        "Missile (Wave Beam)": "Flute",
        "Wave Beam": "Piece Of Heart",
        "Energy Tank, Crocomire": "Super Missile",
        "Missile (above Crocomire)": "Super Missile",
        "Power Bomb (Crocomire)": "Reserve Tank",
        "Missile (below Crocomire)": "Piece Of Heart",
        "Missile (Grapple Beam)": "Progressive Glove",
        "Grapple Beam": "Energy Tank"
    },
    "Lower Norfair": {
        "Missile (Gold Torizo)": "Missile",
        "Super Missile (Gold Torizo)": "Twenty Rupees",
        "Screw Attack": "Ether",
        "Missile (Mickey Mouse room)": "Three Hundred Rupees",
        "Missile (lower Norfair above fire flea room)": "Magic Cape",
        "Power Bomb (lower Norfair above fire flea room)": "Piece Of Heart",
        "Power Bomb (Power Bombs of shame)": "Three Bombs",
        "Missile (lower Norfair near Wave Beam)": "Super Missile",
        "Energy Tank, Ridley": "Progressive Sword",
        "Energy Tank, Firefleas": "Progressive Shield"
    },
    "Wrecked Ship": {
        "Missile (Wrecked Ship middle)": "Ten Arrows",
        "Reserve Tank, Wrecked Ship": "Twenty Rupees",
        "Missile (Gravity Suit)": "Twenty Rupees",
        "Missile (Wrecked Ship top)": "Missile",
        "Energy Tank, Wrecked Ship": "Fifty Rupees",
        "Super Missile (Wrecked Ship left)": "Five Rupees",
        "Right Super, Wrecked Ship": "Magic Mirror",
        "Gravity Suit": "Missile"
    },
    "Maridia": {
        "Missile (green Maridia shinespark)": "Twenty Rupees",
        "Super Missile (green Maridia)": "Bottle (Empty)",
        "Energy Tank, Mama turtle": "Twenty Rupees",
        "Missile (green Maridia tatori)": "Missile",
        "Super Missile (yellow Maridia)": "Piece Of Heart",
        "Missile (yellow Maridia super missile)": "Ice Beam",
        "Missile (yellow Maridia false wall)": "Missile",
        "Plasma Beam": "Super Missile",
        "Missile (left Maridia sand pit room)": "Energy Tank",
        "Reserve Tank, Maridia": "Twenty Rupees",
        "Missile (right Maridia sand pit room)": "Power Bomb",
        "Power Bomb (right Maridia sand pit room)": "Twenty Rupees",
        "Missile (pink Maridia)": "Heart Container",
        "Super Missile (pink Maridia)": "Twenty Rupees",
        "Spring Ball": "Piece Of Heart",
        "Missile (Draygon)": "Piece Of Heart",
        "Energy Tank, Botwoon": "Missile",
        "Space Jump": "One Hundred Rupees"
    },
    "Tourian": [],
    "playthrough": {
        "1": {
            "Light World": {
                "Sahasrahla's Hut - Middle": "Screw Attack",
                "Link's House": "Pegasus Boots",
                "Mini Moldorm Cave - Right": "Power Bomb",
                "Mini Moldorm Cave - Far Right": "Progressive Sword",
                "Mini Moldorm Cave - NPC": "Super Missile"
            },
            "Eastern Palace": {
                "Eastern Palace - Compass Chest": "Eastern Palace Big Key"
            }
        },
        "2": {
            "Light World": {
                "Pegasus Rocks": "Bottle (Golden Bee)",
                "Library": "Reserve Tank"
            },
            "Crateria": {
                "Missile (Crateria bottom)": "Book Of Mudora"
            },
            "Brinstar": {
                "Missile (pink Brinstar top)": "Spring Ball",
                "Missile (pink Brinstar bottom)": "Wave Beam"
            }
        },
        "3": {
            "Light World": {
                "Sick Kid": "Energy Tank",
                "Desert Ledge": "Morphing Ball"
            }
        },
        "4": {
            "Desert Palace": {
                "Desert Palace - Big Key Chest": "Desert Palace Big Key"
            },
            "Crateria": {
                "Missile (outside Wrecked Ship bottom)": "Progressive Glove"
            },
            "Brinstar": {
                "Power Bomb (blue Brinstar)": "Lamp",
                "Missile (red Brinstar spike room)": "Varia Suit",
                "Energy Tank, Kraid": "Cane Of Somaria",
                "Missile (Kraid)": "Progressive Sword",
                "Kraid": "Defeat Kraid"
            },
            "Norfair": {
                "Hi-Jump Boots": "Hookshot"
            },
            "Wrecked Ship": {
                "Right Super, Wrecked Ship": "Magic Mirror",
                "Phantoon": "Defeat Phantoon"
            }
        },
        "5": {
            "Desert Palace": {
                "Desert Palace - Lanmolas'": "Space Jump",
                "Desert Palace - Prize": "Crystal 3"
            },
            "Death Mountain": {
                "Spiral Cave": "Cane Of Byrna",
                "Paradox Cave Lower - Middle": "Hammer"
            }
        },
        "6": {
            "Tower Of Hera": {
                "Tower of Hera - Big Key Chest": "Tower of Hera Big Key"
            },
            "Norfair": {
                "Missile (Speed Booster)": "Speed Booster",
                "Missile (Wave Beam)": "Flute",
                "Missile (Grapple Beam)": "Progressive Glove"
            }
        },
        "7": {
            "Light World": {
                "King's Tomb": "Fire Rod"
            },
            "Tower Of Hera": {
                "Tower of Hera - Prize": "Crystal 6"
            },
            "Crateria": {
                "Super Missile (Crateria)": "Moon Pearl"
            },
            "Lower Norfair": {
                "Screw Attack": "Ether"
            }
        },
        "8": {
            "Dark World": {
                "C-Shaped House": "Ice Rod",
                "Digging Game": "Bow"
            },
            "Dark Palace": {
                "Palace of Darkness - Shooter Room": "Flippers"
            }
        },
        "9": {
            "Eastern Palace": {
                "Eastern Palace - Prize": "Crystal 1"
            },
            "Turtle Rock": {
                "Turtle Rock - Big Key Chest": "Turtle Rock Big Key"
            }
        },
        "10": {
            "Swamp Palace": {
                "Swamp Palace - Compass Chest": "Gravity Suit",
                "Swamp Palace - Prize": "Crystal 7"
            }
        },
        "11": {
            "Dark Palace": {
                "Palace of Darkness - Big Key Chest": "Palace of Darkness Big Key",
                "Palace of Darkness - Dark Maze - Top": "Charge Beam"
            },
            "Misery Mire": {
                "Misery Mire - Compass Chest": "Misery Mire Big Key"
            },
            "Maridia": {
                "Draygon": "Defeat Draygon"
            }
        },
        "12": {
            "Dark Palace": {
                "Palace of Darkness - Prize": "Crystal 5"
            },
            "Misery Mire": {
                "Misery Mire - Prize": "Crystal 2"
            },
            "Turtle Rock": {
                "Turtle Rock - Prize": "Crystal 4"
            },
            "Lower Norfair": {
                "Ridley": "Defeat Ridley"
            }
        },
        "13": {
            "Tourian": {
                "Mother Brain": "Defeat Mother Brain"
            }
        },
        "14": {
            "Ganons Tower": {
                "Ganon's Tower - Hope Room - Right": "Ganons Tower Big Key"
            }
        },
        "15": {
            "Ganons Tower": {
                "Agahnim 2": "Defeat Agahnim 2"
            }
        },
        "16": {
            "Dark World": {
                "Ganon": "Triforce"
            }
        },
        "longest_item_chain": 16,
        "regions_visited": 35
    },
    "meta": {
        "difficulty": "normal",
        "variation": "combo",
        "logic": "alttp-no-glitches-v10",
        "sm_logic": "sm-normal",
        "rom_mode": "NoMajorGlitches",
        "seed": 18254,
        "goal": "ganon",
        "build": "2018-07-22",
        "mode": "open",
        "weapons": "",
        "morph": "randomized"
    }
}

**Comment by CapnCrinklepants** [comment]
Please see Issue #63 . You can cross the moat with Spring Ball. Maybe there's a case to be made for changing the logic up, but since the logic is no longer labeled "casual" and the trick is really pretty easy I think it's reasonable to leave it but that's my 2 cents.
