### ISSUE TITLE
Ice Rod is in Ganon's Tower when Turtle Rock has a crystal

### ISSUE THREAD

**Issue by clozier304** [tewtal/alttp_sm_combo_randomizer#72]
Console or Emulator: Emulator (Snes9x 1.54.1)

Original Filename: SMALttP - sm-normal_alttp-no-glitches-v10_normal-open_swords-randomized_morph-randomized_ganon_combo_593676245

Seed: 593676245

Item, Entrance or Custom: Item

Mode: Normal Super Metroid / No glitches ALTTP
Logic: No Glitches
Goal: Defeat Ganon / MB
Difficulty: Normal
Variation: ALLTP / SM

Description of problem: Ice Rod is in Ganon's Tower, leaving the player unable to defeat Tri-Nex to get the final crystal.

**Comment by Gilgatex** [comment]
In the seed # you gave, it says the Ice Rod is in Kakariko Tavern.  Perhaps you confused it with the Super Metroid Ice Beam, which is in Ganon's Tower?

**Comment by clozier304** [comment]
So it would seem. The perils of highly complex randomizers late at night. Sorry.
