### ISSUE TITLE
Failed to Generate Seed

### ISSUE THREAD

**Issue by Uminojyaku** [tewtal/alttp_sm_combo_randomizer#74]
Not sure if this is a website issue or what. But I can't generate a rom at all.

**Comment by dannyjoejr** [comment]
Also having this issue. Tried deleting cookies, reuploading roms, checked roms on JSFiddle, I turned off all extensions, used incognito, just about everything.
![alttpsmhmpg](https://user-images.githubusercontent.com/13374346/44631603-1b869b00-a934-11e8-82bc-15435f2295be.png)
