### ISSUE TITLE
Impossible Seed?

### ISSUE THREAD

**Issue by qujibo** [tewtal/alttp_sm_combo_randomizer#76]
Console or Emulator: Snesx9-x64

 If emulator state which emulator and version.

Original Filename:

Seed: 930137504

Item, Entrance or Custom: 

Mode: open
Logic: SM-normal, ALttP-no glitches-v10
Goal: Ganon
Difficulty: normal
Variation: combo

Description of problem: Morph ball is held by catfish in dark world. I've got everything in the light world except old man. I checked and he has power bombs which do me no good. So I'm stuck in Criteria in SM and there is nothing in ALttP. Supposed to be a glitchless run too. Tried going to the darkworld on death mountain then saving and quitting and it just puts me back in the light world. Playthrough says I'm supposed to go to red spike room in brinstar but I can't get there because no morph ball. Is there another way to get to the dark world? When I went to the dark world on death mountain a few places on the tracker turned blue which I have never seen before. Am I stuck or am I missing something?

Spoiler (if available):

**Comment by CapnCrinklepants** [comment]
You can get to Red Brinstar Spike Room by using the norfair/death mountain portal, backtracking into red brinstar, then copious use of the ice beam to climb all the way up. From there you can get to brinstar through crateria with a well placed blue suit jump.

These types of questions are better discussed on the discord until it can be confirmed that's a bug. https://discord.gg/9GyKNKt
