### ISSUE TITLE
SM Demo Glitches/Crashes

### ISSUE THREAD

**Issue by SmolBig** [tewtal/alttp_sm_combo_randomizer#78]
As reported by Iris Isotheis in the Discord:

snes9x, v1.56.2
Windows 10

264431011 https://clips.twitch.tv/BovineSpookyAlligatorPupper
997975274 https://clips.twitch.tv/YawningSuccessfulVelociraptorDoggo

"The behaviour it has is consistent if you keep the same seed, but depending of seeds, it may or may not crash or behave weird, if I'm right? I think?"

----
Recommend spending a few minutes trying to find the issue in the debugger, then possibly just altering the timer on the main screen to never enter the demo, or else short-circuiting the demos to return to the main screen.

**Comment by tewtal** [comment]
A patch to disable demos will be included in the next update.
