### ISSUE TITLE
Crateria map progress is erased every time I come back to SM from ALttP

### ISSUE THREAD

**Issue by WVI** [tewtal/alttp_sm_combo_randomizer#8]
Seed is 702254944, not sure if this happens across every seed. If, for example, you take the fortune teller houses back to Brinstar, checking the map will claim you've only been to the room you just came in and a couple tiles above the gunship. if you hit up the Crateria Map Room, the map will be visible, but the progress of rooms turning pink as you explore them will still be reset.

**Comment by tewtal** [comment]
The map issues has been resolved thanks to patches from Lenophis and will be added into the next public release of the randomizer.
