### ISSUE TITLE
Skull Dungeon Big Key in the Big Chest

### ISSUE THREAD

**Issue by Heitomos** [tewtal/alttp_sm_combo_randomizer#81]
Console or Emulator:

 If emulator state which emulator and version.

Original Filename: SMALttP - valttp-no-glitches-v10_normal-open-randomized-ganon_combo_301794147

Seed:

Item, Entrance or Custom: 

Mode: Normal
Logic: Normal
Goal: Normal
Difficulty: Normal
Variation: Normal

Description of problem: The Big Key for the Skull Dungeon is located in the Big Chest, making the game unplayable.

Spoiler (if available):
[SMALttP - valttp-no-glitches-v10_normal-open-randomized-ganon_combo_301794147.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2442606/SMALttP.-.valttp-no-glitches-v10_normal-open-randomized-ganon_combo_301794147.txt)

**Comment by Gilgatex** [comment]
How does this make the game unplayable?  You don't need the big key to beat the dungeon or to get any of the items in it other than the big chest itself.  This is intended behavior.
