### ISSUE TITLE
Trouble Creating Seed on Site.

### ISSUE THREAD

**Issue by butterscotchandwater** [tewtal/alttp_sm_combo_randomizer#82]
So I went to the alttpsm website to create a seed. Added both roms (Which I checked to make sure they were the appropriate roms, they seem to be) Multiple tries and it just says Failed creating seed. I went around to see if I could find the answer to my problem and actually seems like multiple people are experiencing this. One person replied to me on reddit saying they went to try to make a seed after I posted and got the same outcome. Some on discord said they were getting the same error as well.

**Comment by tewtal** [comment]
There was an issue with disk space on the site, it's been resolved now.
