### ISSUE TITLE
Inner Maridia missing explicit Supers requirement

### ISSUE THREAD

**Issue by miketrethewey** [tewtal/alttp_sm_combo_randomizer#83]
Sand Pit Rooms, Reserve Tank, and anything in and beyond [Aqueduct](http://wiki.supermetroid.run/Aqueduct) don't explicitly require `Supers` in their local location access logic. [(src)](https://github.com/tewtal/alttp_sm_combo_randomizer/blob/6ed3be03576c666aa0ee97524c5f373cf4eff1ea/app/Region/SuperMetroid/Maridia/Inner.php)
Sand Pit Rooms & Reserve Tank require `Supers` for leaving. (Thanks, Natalie!)
Inner Maridia access logic doesn't explicitly require `Supers`.
Inner Maridia access logic does refer to the Norfair Portal which needs Death Mountain access.
Inner Maridia access logic does refer to Norfair West access which does have `Supers`, but is only checked if the Norfair Portal cannot be accessed from the Hyrule side.

# Sand Pit Logic
## Tournament
```diff
		$this->locations["Missile (left Maridia sand pit room)"]->setRequirements(function($location, $items) {
-			return ($items->has('HiJump') && ($items->has('SpaceJump') || $items->canSpringBallJump())) || $items->has('Gravity');
+			return $items->has('Super') && (($items->has('HiJump') && ($items->has('SpaceJump') || $items->canSpringBallJump())) || $items->has('Gravity'));
		});
		$this->locations["Reserve Tank, Maridia"]->setRequirements(function($location, $items) {
-			return ($items->has('HiJump') && ($items->has('SpaceJump') || $items->canSpringBallJump())) || $items->has('Gravity');
+			return $items->has('Super') && (($items->has('HiJump') && ($items->has('SpaceJump') || $items->canSpringBallJump())) || $items->has('Gravity'));
		});
		$this->locations["Missile (right Maridia sand pit room)"]->setRequirements(function($location, $items) {
-			return $items->has('HiJump') || $items->has('Gravity');
+			return $items->has('Super') && ($items->has('HiJump') || $items->has('Gravity'));
		});
        	$this->locations["Power Bomb (right Maridia sand pit room)"]->setRequirements(function($location, $items) {
-			return ($items->has('HiJump') && $items->canSpringBallJump()) || $items->has('Gravity');
+			return $items->has('Super') && (($items->has('HiJump') && $items->canSpringBallJump()) || $items->has('Gravity'));
		});
```
## Casual
```diff
		$this->locations["Missile (left Maridia sand pit room)"]->setRequirements(function($location, $items) {
-			return $items->canPassBombPassages();
+			return $items->has('Super') && $items->canPassBombPassages());
		});
		$this->locations["Reserve Tank, Maridia"]->setRequirements(function($location, $items) {
-			return $items->canPassBombPassages();
+			return $items->has('Super') && $items->canPassBombPassages();
		});
```
# Coded path
* Access to Maridia tube
  * Travel through Brinstar (Requires `Supers`)
    * `((Morph && Bombs) || Speed)` to Terminator
    * `Super` to get through Red & Green Missile Doors
    * Travel through Green Brin to Pink Brin
    * Go to bottom of Big Pink
    * Head through Green Hill Zone
    * Head down Red Tower
    * Shoot shot blocks to continue heading down
  * Take the Norfair Portal from Death Mountain (Doesn't require `Supers`)
    * `Flute || (Lamp && Glove)`
* `Powers` to blow the tube
* `Gravity` for movement

# Intended path
* Same as above
* `Supers` to blast Green Door between Mt. Everest & Aqueduct
  * Stuck if came from Norfair Portal with no `Supers`

# Suggested solution
The above `diff`s and...
The following locations:
* Missile (pink Maridia)
* Super Missile (pink Maridia)
* Spring Ball
* Missile (Draygon)
* Energy Tank, Botwoon
* Space Jump

Shoud get a check like:
```php
if($items->canAccessNorfairPortal()) {
  // require Supers in addition to the rest of the local requirements
}
```

**Comment by fdtaillefer** [comment]
My proposed fix deviates a bit from the suggested solution:
- Supers added to the front-side access part of `can_enter`
- No specific changes directly on the two aqueduct checks because they are covered by `can_enter`
- Besides the 4 sand pit checks, Supers added explicitly to the Spring Ball spot because you can't escape that one either without Supers
