### ISSUE TITLE
Blue Brinstar Missle Top Req

### ISSUE THREAD

**Issue by SamRCawley** [tewtal/alttp_sm_combo_randomizer#88]
Seed: 691739703

Mode: No Glitches
Logic:  Normal
Goal:  Defeat Ganon and Mother Brain
Difficulty: Normal
Variation:  ALTTP+SM

Description of problem:  The blue brinstar double missile room appears to have bugged requirements on normal.  The seed only gives speed and the ability to open the door (which seems within the code's logic), but there doesn't seem to be a way onto the invisible platform without jump boots or gravity suit.  A short charge shinespark could probably do it, but that's above normal tricks.

Spoiler (if available):
`{
    "Light World": {
        "Sahasrahla's Hut - Left": "Ten Arrows",
        "Sahasrahla's Hut - Middle": "Super Missile",
        "Sahasrahla's Hut - Right": "Twenty Rupees",
        "Sahasrahla": "Twenty Rupees",
        "King Zora": "Missile",
        "Potion Shop": "Three Hundred Rupees",
        "Zora's Ledge": "Progressive Sword",
        "Waterfall Fairy - Left": "Super Missile",
        "Waterfall Fairy - Right": "Reserve Tank",
        "Master Sword Pedestal": "Magic Cape",
        "King's Tomb": "Fifty Rupees",
        "Kakariko Tavern": "Twenty Rupees",
        "Chicken House": "Ice Beam",
        "Kakariko Well - Top": "Sancturary Heart Container",
        "Kakariko Well - Left": "Piece Of Heart",
        "Kakariko Well - Middle": "Morphing Ball",
        "Kakariko Well - Right": "Super Missile",
        "Kakariko Well - Bottom": "Missile",
        "Blind's Hideout - Top": "Bomb Upgrade (+10)",
        "Blind's Hideout - Left": "Piece Of Heart",
        "Blind's Hideout - Right": "Progressive Shield",
        "Blind's Hideout - Far Left": "Five Rupees",
        "Blind's Hideout - Far Right": "Missile",
        "Pegasus Rocks": "Super Missile",
        "Bottle Merchant": "Twenty Rupees",
        "Magic Bat": "Missile",
        "Sick Kid": "Twenty Rupees",
        "Lost Woods Hideout": "Bottle (Fairy)",
        "Lumberjack Tree": "Three Bombs",
        "Graveyard Ledge": "Fifty Rupees",
        "Mushroom": "Bomb Upgrade (+5)",
        "Floodgate Chest": "Reserve Tank",
        "Link's House": "Three Hundred Rupees",
        "Aginah's Cave": "Bottle (Red Potion)",
        "Mini Moldorm Cave - Far Left": "Progressive Armor",
        "Mini Moldorm Cave - Left": "Spazer",
        "Mini Moldorm Cave - Right": "Energy Tank",
        "Mini Moldorm Cave - Far Right": "Energy Tank",
        "Ice Rod Cave": "Missile",
        "Hobo": "Twenty Rupees",
        "Bombos Tablet": "Three Hundred Rupees",
        "Cave 45": "One Hundred Rupees",
        "Checkerboard Cave": "Twenty Rupees",
        "Mini Moldorm Cave - NPC": "Three Bombs",
        "Library": "Twenty Rupees",
        "Maze Race": "Piece Of Heart",
        "Desert Ledge": "Moon Pearl",
        "Lake Hylia Island": "One Rupee",
        "Sunken Treasure": "Three Bombs",
        "Flute Spot": "Heart Container"
    },
    "Hyrule Castle": {
        "Sanctuary": "Sewers Map",
        "Sewers - Secret Room - Left": "Missile",
        "Sewers - Secret Room - Middle": "Hookshot",
        "Sewers - Secret Room - Right": "Fifty Rupees",
        "Sewers - Dark Cross": "Flippers",
        "Hyrule Castle - Boomerang Chest": "Energy Tank",
        "Hyrule Castle - Map Chest": "Sewers Key",
        "Hyrule Castle - Zelda's Cell": "Progressive Glove",
        "Link's Uncle": "Progressive Shield",
        "Secret Passage": "Bow"
    },
    "Eastern Palace": {
        "Eastern Palace - Compass Chest": "Three Hundred Rupees",
        "Eastern Palace - Big Chest": "Eastern Palace Compass",
        "Eastern Palace - Cannonball Chest": "Eastern Palace Map",
        "Eastern Palace - Big Key Chest": "Eastern Palace Big Key",
        "Eastern Palace - Map Chest": "Missile",
        "Eastern Palace - Armos Knights": "Arrow Upgrade (+5)",
        "Eastern Palace - Prize": "Crystal 1"
    },
    "Desert Palace": {
        "Desert Palace - Big Chest": "Desert Palace Key",
        "Desert Palace - Map Chest": "Missile",
        "Desert Palace - Torch": "Desert Palace Big Key",
        "Desert Palace - Big Key Chest": "Desert Palace Compass",
        "Desert Palace - Compass Chest": "Desert Palace Map",
        "Desert Palace - Lanmolas'": "Twenty Rupees",
        "Desert Palace - Prize": "Crystal 3"
    },
    "Death Mountain": {
        "Old Man": "Heart Container",
        "Spectacle Rock Cave": "Arrow Upgrade (+5)",
        "Ether Tablet": "Energy Tank",
        "Spectacle Rock": "Energy Tank",
        "Spiral Cave": "Arrow Upgrade (+10)",
        "Mimic Cave": "Power Bomb",
        "Paradox Cave Lower - Far Left": "Progressive Sword",
        "Paradox Cave Lower - Left": "Twenty Rupees",
        "Paradox Cave Lower - Right": "Heart Container",
        "Paradox Cave Lower - Far Right": "Twenty Rupees",
        "Paradox Cave Lower - Middle": "Power Bomb",
        "Paradox Cave Upper - Left": "Energy Tank",
        "Paradox Cave Upper - Right": "Missile",
        "Floating Island": "Power Bomb"
    },
    "Tower Of Hera": {
        "Tower of Hera - Big Key Chest": "Tower of Hera Big Key",
        "Tower of Hera - Basement Cage": "Tower of Hera Key",
        "Tower of Hera - Map Chest": "Tower of Hera Compass",
        "Tower of Hera - Compass Chest": "Half Magic",
        "Tower of Hera - Big Chest": "Tower of Hera Map",
        "Tower of Hera - Moldorm": "Piece Of Heart",
        "Tower of Hera - Prize": "Crystal 7"
    },
    "Castle Tower": {
        "Castle Tower - Room 03": "Agahnims Tower Key",
        "Castle Tower - Dark Maze": "Agahnims Tower Key"
    },
    "Dark World": {
        "Superbunny Cave - Top": "Missile",
        "Superbunny Cave - Bottom": "Power Bomb",
        "Hookshot Cave - Top Right": "Missile",
        "Hookshot Cave - Top Left": "Piece Of Heart",
        "Hookshot Cave - Bottom Left": "Twenty Rupees",
        "Hookshot Cave - Bottom Right": "Quake",
        "Spike Cave": "Arrow Upgrade (+5)",
        "Catfish": "Twenty Rupees",
        "Pyramid": "Fire Rod",
        "Pyramid Fairy - Left": "Power Bomb",
        "Pyramid Fairy - Right": "Missile",
        "Brewery": "Super Missile",
        "C-Shaped House": "Piece Of Heart",
        "Chest Game": "Hi-Jump Boots",
        "Hammer Pegs": "Varia Suit",
        "Bumper Cave": "Missile",
        "Blacksmith": "Missile",
        "Purple Chest": "Missile",
        "Hype Cave - Top": "Piece Of Heart",
        "Hype Cave - Middle Right": "Energy Tank",
        "Hype Cave - Middle Left": "Three Bombs",
        "Hype Cave - Bottom": "Arrow Upgrade (+5)",
        "Stumpy": "Super Missile",
        "Hype Cave - NPC": "Missile",
        "Digging Game": "Bottle (Bee)",
        "Mire Shed - Left": "Energy Tank",
        "Mire Shed - Right": "One Rupee"
    },
    "Dark Palace": {
        "Palace of Darkness - Shooter Room": "Palace of Darkness Big Key",
        "Palace of Darkness - Big Key Chest": "Palace of Darkness Key",
        "Palace of Darkness - The Arena - Ledge": "Palace of Darkness Key",
        "Palace of Darkness - The Arena - Bridge": "Palace of Darkness Key",
        "Palace of Darkness - Stalfos Basement": "Heart Container",
        "Palace of Darkness - Map Chest": "Palace of Darkness Key",
        "Palace of Darkness - Big Chest": "Palace of Darkness Compass",
        "Palace of Darkness - Compass Chest": "Bomb Upgrade (+5)",
        "Palace of Darkness - Harmless Hellway": "Palace of Darkness Key",
        "Palace of Darkness - Dark Basement - Left": "Palace of Darkness Key",
        "Palace of Darkness - Dark Basement - Right": "Palace of Darkness Map",
        "Palace of Darkness - Dark Maze - Top": "Ether",
        "Palace of Darkness - Dark Maze - Bottom": "Energy Tank",
        "Palace of Darkness - Helmasaur King": "Piece Of Heart",
        "Palace of Darkness - Prize": "Pendant Of Power"
    },
    "Swamp Palace": {
        "Swamp Palace - Entrance": "Swamp Palace Key",
        "Swamp Palace - Big Chest": "Swamp Palace Big Key",
        "Swamp Palace - Big Key Chest": "Heart Container",
        "Swamp Palace - Map Chest": "Twenty Rupees",
        "Swamp Palace - West Chest": "Swamp Palace Compass",
        "Swamp Palace - Compass Chest": "Progressive Sword",
        "Swamp Palace - Flooded Room - Left": "Swamp Palace Map",
        "Swamp Palace - Flooded Room - Right": "Ice Rod",
        "Swamp Palace - Waterfall Room": "Twenty Rupees",
        "Swamp Palace - Arrghus": "Arrow Upgrade (+5)",
        "Swamp Palace - Prize": "Pendant Of Courage"
    },
    "Skull Woods": {
        "Skull Woods - Big Chest": "Skull Woods Big Key",
        "Skull Woods - Big Key Chest": "Skull Woods Key",
        "Skull Woods - Compass Chest": "Skull Woods Map",
        "Skull Woods - Map Chest": "Skull Woods Compass",
        "Skull Woods - Bridge Room": "Heart Container",
        "Skull Woods - Pot Prison": "Skull Woods Key",
        "Skull Woods - Pinball Room": "Skull Woods Key",
        "Skull Woods - Mothula": "Piece Of Heart",
        "Skull Woods - Prize": "Crystal 2"
    },
    "Thieves Town": {
        "Thieves' Town - Attic": "Thieves Town Compass",
        "Thieves' Town - Big Key Chest": "Gravity Suit",
        "Thieves' Town - Map Chest": "Thieves Town Big Key",
        "Thieves' Town - Compass Chest": "Thieves Town Map",
        "Thieves' Town - Ambush Chest": "Shovel",
        "Thieves' Town - Big Chest": "Grappling Beam",
        "Thieves' Town - Blind's Cell": "Thieves Town Key",
        "Thieves' Town - Blind": "Three Bombs",
        "Thieves' Town - Prize": "Crystal 6"
    },
    "Ice Palace": {
        "Ice Palace - Big Key Chest": "Missile",
        "Ice Palace - Compass Chest": "Ice Palace Map",
        "Ice Palace - Map Chest": "Ice Palace Compass",
        "Ice Palace - Spike Room": "Missile",
        "Ice Palace - Freezor Chest": "Ice Palace Big Key",
        "Ice Palace - Iced T Room": "Ice Palace Key",
        "Ice Palace - Big Chest": "Ice Palace Key",
        "Ice Palace - Kholdstare": "Missile",
        "Ice Palace - Prize": "Crystal 5"
    },
    "Misery Mire": {
        "Misery Mire - Big Chest": "Misery Mire Map",
        "Misery Mire - Main Lobby": "Misery Mire Compass",
        "Misery Mire - Big Key Chest": "Piece Of Heart",
        "Misery Mire - Compass Chest": "Heart Container",
        "Misery Mire - Bridge Chest": "Misery Mire Key",
        "Misery Mire - Map Chest": "Misery Mire Key",
        "Misery Mire - Spike Chest": "Misery Mire Big Key",
        "Misery Mire - Vitreous": "Misery Mire Key",
        "Misery Mire - Prize": "Pendant Of Wisdom"
    },
    "Turtle Rock": {
        "Turtle Rock - Chain Chomps": "Turtle Rock Key",
        "Turtle Rock - Compass Chest": "Turtle Rock Key",
        "Turtle Rock - Roller Room - Left": "Super Missile",
        "Turtle Rock - Roller Room - Right": "Turtle Rock Map",
        "Turtle Rock - Big Chest": "Turtle Rock Key",
        "Turtle Rock - Big Key Chest": "Turtle Rock Big Key",
        "Turtle Rock - Crystaroller Room": "Spring Ball",
        "Turtle Rock - Eye Bridge - Bottom Left": "Missile",
        "Turtle Rock - Eye Bridge - Bottom Right": "Turtle Rock Key",
        "Turtle Rock - Eye Bridge - Top Left": "Ten Arrows",
        "Turtle Rock - Eye Bridge - Top Right": "Turtle Rock Compass",
        "Turtle Rock - Trinexx": "Super Missile",
        "Turtle Rock - Prize": "Crystal 4"
    },
    "Ganons Tower": {
        "Ganon's Tower - Bob's Torch": "Twenty Rupees",
        "Ganon's Tower - DMs Room - Top Left": "Ganons Tower Key",
        "Ganon's Tower - DMs Room - Top Right": "Piece Of Heart",
        "Ganon's Tower - DMs Room - Bottom Left": "Missile",
        "Ganon's Tower - DMs Room - Bottom Right": "Ten Arrows",
        "Ganon's Tower - Randomizer Room - Top Left": "Progressive Shield",
        "Ganon's Tower - Randomizer Room - Top Right": "Missile",
        "Ganon's Tower - Randomizer Room - Bottom Left": "Bottle (Green Potion)",
        "Ganon's Tower - Randomizer Room - Bottom Right": "Ganons Tower Big Key",
        "Ganon's Tower - Firesnake Room": "Twenty Rupees",
        "Ganon's Tower - Map Chest": "Missile",
        "Ganon's Tower - Big Chest": "Cane Of Byrna",
        "Ganon's Tower - Hope Room - Left": "Ganons Tower Key",
        "Ganon's Tower - Hope Room - Right": "Twenty Rupees",
        "Ganon's Tower - Bob's Chest": "Blue Boomerang",
        "Ganon's Tower - Tile Room": "Ganons Tower Key",
        "Ganon's Tower - Compass Room - Top Left": "Missile",
        "Ganon's Tower - Compass Room - Top Right": "Bomb Upgrade (+5)",
        "Ganon's Tower - Compass Room - Bottom Left": "Power Bomb",
        "Ganon's Tower - Compass Room - Bottom Right": "Energy Tank",
        "Ganon's Tower - Big Key Chest": "Ganons Tower Key",
        "Ganon's Tower - Big Key Room - Left": "Ganons Tower Map",
        "Ganon's Tower - Big Key Room - Right": "Fifty Rupees",
        "Ganon's Tower - Mini Helmasaur Room - Left": "Silver Arrows Upgrade",
        "Ganon's Tower - Mini Helmasaur Room - Right": "Heart Container",
        "Ganon's Tower - Pre-Moldorm Chest": "Ganons Tower Compass",
        "Ganon's Tower - Moldorm Chest": "Magical Boomerang"
    },
    "Special": {
        "Turtle Rock Medallion": "Quake",
        "Misery Mire Medallion": "Quake",
        "Waterfall Bottle": "Bottle (Golden Bee)",
        "Pyramid Bottle": "Bottle (Blue Potion)"
    },
    "Crateria": {
        "Power Bomb (Crateria surface)": "Twenty Rupees",
        "Missile (Crateria middle)": "Piece Of Heart",
        "Missile (Crateria bottom)": "Bomb Upgrade (+5)",
        "Super Missile (Crateria)": "Fifty Rupees",
        "Bombs": "Bomb Upgrade (+5)",
        "Energy Tank, Terminator": "Twenty Rupees",
        "Energy Tank, Gauntlet": "Missile",
        "Missile (Crateria gauntlet right)": "Piece Of Heart",
        "Missile (Crateria gauntlet left)": "Lamp",
        "Missile (outside Wrecked Ship bottom)": "Five Rupees",
        "Missile (outside Wrecked Ship top)": "Reserve Tank",
        "Missile (outside Wrecked Ship middle)": "Charge Beam",
        "Missile (Crateria moat)": "Missile"
    },
    "Brinstar": {
        "Power Bomb (green Brinstar bottom)": "Piece Of Heart",
        "Missile (green Brinstar below super missile)": "Missile",
        "Super Missile (green Brinstar top)": "Super Missile",
        "Reserve Tank, Brinstar": "Piece Of Heart",
        "Missile (green Brinstar behind missile)": "Piece Of Heart",
        "Missile (green Brinstar behind reserve tank)": "Energy Tank",
        "Energy Tank, Etecoons": "Progressive Sword",
        "Super Missile (green Brinstar bottom)": "Piece Of Heart",
        "Super Missile (pink Brinstar)": "Missile",
        "Missile (pink Brinstar top)": "Missile",
        "Missile (pink Brinstar bottom)": "Twenty Rupees",
        "Charge Beam": "Plasma Beam",
        "Power Bomb (pink Brinstar)": "Arrow Upgrade (+5)",
        "Missile (green Brinstar pipe)": "Five Rupees",
        "Energy Tank, Waterway": "Bombs",
        "Energy Tank, Brinstar Gate": "Missile",
        "Morphing Ball": "Piece Of Heart",
        "Power Bomb (blue Brinstar)": "Ten Bombs",
        "Missile (blue Brinstar middle)": "Flute",
        "Energy Tank, Brinstar Ceiling": "Piece Of Heart",
        "Missile (blue Brinstar bottom)": "Energy Tank",
        "Missile (blue Brinstar top)": "Hammer",
        "Missile (blue Brinstar behind missile)": "Book Of Mudora",
        "X-Ray Scope": "Super Missile",
        "Power Bomb (red Brinstar sidehopper room)": "Three Bombs",
        "Power Bomb (red Brinstar spike room)": "Speed Booster",
        "Missile (red Brinstar spike room)": "Pegasus Boots",
        "Spazer": "Missile",
        "Energy Tank, Kraid": "Five Rupees",
        "Varia Suit": "Energy Tank",
        "Missile (Kraid)": "Power Bomb"
    },
    "Norfair": {
        "Ice Beam": "Piece Of Heart",
        "Missile (below Ice Beam)": "Missile",
        "Hi-Jump Boots": "Three Bombs",
        "Missile (Hi-Jump Boots)": "Mushroom",
        "Energy Tank (Hi-Jump Boots)": "Fifty Rupees",
        "Missile (lava room)": "X-Ray Scope",
        "Reserve Tank, Norfair": "Bombos",
        "Missile (Norfair Reserve Tank)": "Three Hundred Rupees",
        "Missile (bubble Norfair green door)": "Twenty Rupees",
        "Missile (bubble Norfair)": "Three Bombs",
        "Missile (Speed Booster)": "Missile",
        "Speed Booster": "Twenty Rupees",
        "Missile (Wave Beam)": "Missile",
        "Wave Beam": "Heart Container",
        "Energy Tank, Crocomire": "Power Bomb",
        "Missile (above Crocomire)": "Missile",
        "Power Bomb (Crocomire)": "Missile",
        "Missile (below Crocomire)": "Progressive Armor",
        "Missile (Grapple Beam)": "Super Missile",
        "Grapple Beam": "Piece Of Heart"
    },
    "Lower Norfair": {
        "Missile (Gold Torizo)": "Power Bomb",
        "Super Missile (Gold Torizo)": "Screw Attack",
        "Screw Attack": "Energy Tank",
        "Missile (Mickey Mouse room)": "Super Missile",
        "Missile (lower Norfair above fire flea room)": "Twenty Rupees",
        "Power Bomb (lower Norfair above fire flea room)": "Magic Mirror",
        "Power Bomb (Power Bombs of shame)": "Twenty Rupees",
        "Missile (lower Norfair near Wave Beam)": "Missile",
        "Energy Tank, Ridley": "Piece Of Heart",
        "Energy Tank, Firefleas": "Wave Beam"
    },
    "Wrecked Ship": {
        "Missile (Wrecked Ship middle)": "Piece Of Heart",
        "Reserve Tank, Wrecked Ship": "Three Bombs",
        "Missile (Gravity Suit)": "Single Arrow",
        "Missile (Wrecked Ship top)": "Super Missile",
        "Energy Tank, Wrecked Ship": "Ten Arrows",
        "Super Missile (Wrecked Ship left)": "Missile",
        "Right Super, Wrecked Ship": "Power Bomb",
        "Gravity Suit": "Super Missile"
    },
    "Maridia": {
        "Missile (green Maridia shinespark)": "Piece Of Heart",
        "Super Missile (green Maridia)": "Super Missile",
        "Energy Tank, Mama turtle": "Fifty Rupees",
        "Missile (green Maridia tatori)": "Missile",
        "Super Missile (yellow Maridia)": "Ten Arrows",
        "Missile (yellow Maridia super missile)": "Super Missile",
        "Missile (yellow Maridia false wall)": "Space Jump",
        "Plasma Beam": "Magic Powder",
        "Missile (left Maridia sand pit room)": "Progressive Glove",
        "Reserve Tank, Maridia": "Bomb Upgrade (+5)",
        "Missile (right Maridia sand pit room)": "Super Missile",
        "Power Bomb (right Maridia sand pit room)": "Heart Container",
        "Missile (pink Maridia)": "Twenty Rupees",
        "Super Missile (pink Maridia)": "Bug Catching Net",
        "Spring Ball": "Twenty Rupees",
        "Missile (Draygon)": "Cane Of Somaria",
        "Energy Tank, Botwoon": "Twenty Rupees",
        "Space Jump": "Reserve Tank"
    },
    "Tourian": [],
    "playthrough": {
        "1": {
            "Light World": {
                "Chicken House": "Ice Beam",
                "Kakariko Well - Middle": "Morphing Ball",
                "Kakariko Well - Right": "Super Missile",
                "Mini Moldorm Cave - Right": "Energy Tank",
                "Mini Moldorm Cave - Far Right": "Energy Tank"
            },
            "Hyrule Castle": {
                "Secret Passage": "Bow"
            }
        },
        "2": {
            "Hyrule Castle": {
                "Hyrule Castle - Zelda's Cell": "Progressive Glove"
            },
            "Brinstar": {
                "Missile (blue Brinstar middle)": "Flute"
            }
        },
        "3": {
            "Hyrule Castle": {
                "Sewers - Secret Room - Middle": "Hookshot"
            },
            "Brinstar": {
                "Power Bomb (red Brinstar spike room)": "Speed Booster"
            }
        },
        "4": {
            "Death Mountain": {
                "Paradox Cave Lower - Far Left": "Progressive Sword",
                "Paradox Cave Lower - Middle": "Power Bomb"
            }
        },
        "5": {
            "Crateria": {
                "Missile (outside Wrecked Ship middle)": "Charge Beam"
            },
            "Brinstar": {
                "Energy Tank, Etecoons": "Progressive Sword",
                "Energy Tank, Waterway": "Bombs",
                "Missile (blue Brinstar top)": "Hammer",
                "Missile (blue Brinstar behind missile)": "Book Of Mudora",
                "Missile (red Brinstar spike room)": "Pegasus Boots",
                "Kraid": "Defeat Kraid"
            },
            "Wrecked Ship": {
                "Phantoon": "Defeat Phantoon"
            }
        },
        "6": {
            "Light World": {
                "Desert Ledge": "Moon Pearl"
            },
            "Desert Palace": {
                "Desert Palace - Torch": "Desert Palace Big Key"
            },
            "Crateria": {
                "Missile (Crateria gauntlet left)": "Lamp"
            }
        },
        "7": {
            "Hyrule Castle": {
                "Sewers - Dark Cross": "Flippers"
            },
            "Eastern Palace": {
                "Eastern Palace - Big Key Chest": "Eastern Palace Big Key"
            },
            "Tower Of Hera": {
                "Tower of Hera - Big Key Chest": "Tower of Hera Big Key"
            },
            "Dark World": {
                "Pyramid": "Fire Rod"
            },
            "Dark Palace": {
                "Palace of Darkness - Shooter Room": "Palace of Darkness Big Key"
            },
            "Thieves Town": {
                "Thieves' Town - Big Key Chest": "Gravity Suit",
                "Thieves' Town - Map Chest": "Thieves Town Big Key"
            }
        },
        "8": {
            "Eastern Palace": {
                "Eastern Palace - Prize": "Crystal 1"
            },
            "Desert Palace": {
                "Desert Palace - Prize": "Crystal 3"
            },
            "Tower Of Hera": {
                "Tower of Hera - Prize": "Crystal 7"
            },
            "Skull Woods": {
                "Skull Woods - Prize": "Crystal 2"
            },
            "Maridia": {
                "Missile (left Maridia sand pit room)": "Progressive Glove",
                "Missile (Draygon)": "Cane Of Somaria",
                "Draygon": "Defeat Draygon"
            }
        },
        "9": {
            "Dark World": {
                "Hookshot Cave - Bottom Right": "Quake",
                "Hammer Pegs": "Varia Suit"
            },
            "Thieves Town": {
                "Thieves' Town - Prize": "Crystal 6"
            },
            "Ice Palace": {
                "Ice Palace - Freezor Chest": "Ice Palace Big Key"
            }
        },
        "10": {
            "Dark Palace": {
                "Palace of Darkness - Prize": "Pendant Of Power"
            },
            "Ice Palace": {
                "Ice Palace - Prize": "Crystal 5"
            },
            "Misery Mire": {
                "Misery Mire - Spike Chest": "Misery Mire Big Key"
            },
            "Lower Norfair": {
                "Power Bomb (lower Norfair above fire flea room)": "Magic Mirror",
                "Ridley": "Defeat Ridley"
            }
        },
        "11": {
            "Misery Mire": {
                "Misery Mire - Prize": "Pendant Of Wisdom"
            },
            "Tourian": {
                "Mother Brain": "Defeat Mother Brain"
            }
        },
        "12": {
            "Swamp Palace": {
                "Swamp Palace - Flooded Room - Right": "Ice Rod",
                "Swamp Palace - Prize": "Pendant Of Courage"
            },
            "Turtle Rock": {
                "Turtle Rock - Big Key Chest": "Turtle Rock Big Key"
            }
        },
        "13": {
            "Light World": {
                "Master Sword Pedestal": "Magic Cape"
            }
        },
        "14": {
            "Turtle Rock": {
                "Turtle Rock - Prize": "Crystal 4"
            }
        },
        "15": {
            "Ganons Tower": {
                "Ganon's Tower - Randomizer Room - Bottom Right": "Ganons Tower Big Key"
            }
        },
        "16": {
            "Ganons Tower": {
                "Agahnim 2": "Defeat Agahnim 2"
            }
        },
        "17": {
            "Dark World": {
                "Ganon": "Triforce"
            }
        },
        "longest_item_chain": 17,
        "regions_visited": 40
    },
    "meta": {
        "difficulty": "normal",
        "variation": "combo",
        "logic": "alttp-no-glitches-v10",
        "sm_logic": "sm-normal",
        "rom_mode": "NoMajorGlitches",
        "seed": 691739703,
        "goal": "ganon",
        "build": "2018-07-22",
        "mode": "open",
        "weapons": "randomized",
        "morph": "randomized"
    }
}`

**Comment by bluedart** [comment]
Thanks for this.  I was about to open an issue where the Gravity Suit is purportedly required (by a site listed in the Super Metroid x ALttP Resources google doc) to get the Gravity Suit, but this worked, so thank you very much.
