### ISSUE TITLE
Losing Silver Arrows in ALttP

### ISSUE THREAD

**Issue by MSKain** [tewtal/alttp_sm_combo_randomizer#98]
Console or Emulator: SNES9x-x64 v. 1.56.1

 If emulator state which emulator and version.

Original Filename:
SMALttP - sm-normal_alttp-no-glitches-v10.1_normal-open_swords-randomized_morph-randomized_ganon_combo_256980471

Seed:256980471

Item, Entrance or Custom: SM+ALttP combo

Mode: normal
Logic: normal
Goal: Defeat Ganon and Motherbrain
Difficulty: normal
Variation: SM+ALttP Combo Randomizer

Description of problem: This is now the third time (third different Seed) that this has happened to me.  If I collect the Silver Arrows in ALttP first and then collect the Bow in SM, when I transition to ALttP my arrows revert to being normal arrows and I permanently lose Silver Arrows.

Spoiler (if available):
[SMALttP - sm-normal_alttp-no-glitches-v10.1_normal-open_swords-randomized_morph-randomized_ganon_combo_256980471.txt](https://github.com/tewtal/alttp_sm_combo_randomizer/files/2706332/SMALttP.-.sm-normal_alttp-no-glitches-v10.1_normal-open_swords-randomized_morph-randomized_ganon_combo_256980471.txt)

**Comment by alercah** [comment]
You have to press Y on the wooden arrows to switch back to silver.

**Comment by MSKain** [comment]
Oh, thank you!


Sent from Yahoo Mail for iPhone


On Wednesday, December 26, 2018, 6:09 PM, Alexis Hunt <notifications@github.com> wrote:


You have to press Y on the wooden arrows to switch back to silver.
